### ISSUE TITLE
How should we handle "level"/stability of features?

### ISSUE THREAD

**Issue by MoOx** [MoOx/postcss-cssnext#100]
http://babeljs.io/docs/usage/experimental/

Reference: http://www.w3.org/Style/CSS/current-work#legend

```
Stage 0 - Unofficial draft (that's where it's interesting for users)
Stage 1 - working draft
Stage 2 - last call before candidate recommendation
Stage 3 - candidate recommendation
Stage 4 - proposed recommendation
Stage 5 - recommendation
```

It's a lot. Maybe too much ?

**Comment by MoOx** [comment]
Also that might helps for some possible feature https://github.com/postcss/postcss/issues/140

**Comment by magsout** [comment]
it's interesting and I like the idea.

>It's a lot. Maybe too much ?

it is the standard w3c...

**Comment by magsout** [comment]
List of some css4 selectors http://css4.rocks/css4-selectors/

**Comment by MoOx** [comment]
Hum not sure what you mean. cssnext is about the syntax and might not handle a lot of new selector (except :matches maybe).

**Comment by MoOx** [comment]
oups

**Comment by magsout** [comment]
it's just to give plugin ideas that can be created

**Comment by magsout** [comment]
https://github.com/cssnext/cssnext/issues/106 and https://github.com/cssnext/cssnext/issues/17

**Comment by MoOx** [comment]
yes sure. And #80

**Comment by jonathanKingston** [comment]
Certainly #80 would be something that is most important to be excluded due to it being 0.

I think this makes more sense than turning off individual filters so no seems complete sense and not too much.

**Comment by Macxim** [comment]
It's an interesting idea. I don't think it's too much at all. As @magsout pointed, it matches the W3C specs which is consistent with the main purpose of the entire project.

**Comment by MoOx** [comment]
plugin has a 2.0 version that fix some issues.

**Comment by MoOx** [comment]
I just took a second look and found this:
- last call are just considered as WD: "Document maturity level: Working Draft."
- I didn't see a lot of "proposed recommendation" on this page http://www.w3.org/TR/tr-groups-all#tr_Cascading_Style_Sheets__CSS__Working_Group


So what about this:

    Stage 0 - Strawman
    Stage 1 - Unofficial draft
    Stage 2 - Working draft
    Stage 3 - Candidate recommendation
    Stage 4 - Recommendation

Default to 2

Just a rip of babel stages :)

**Comment by magsout** [comment]
👍

**Comment by kaelig** [comment]
Seems like a great idea. :+1:

**Comment by MoOx** [comment]
This way to handle the "issue" seems compromised. See how babel will evolve https://github.com/babel/babel/issues/2168.
I opened a discussion on PostCSS repo to discuss about some things I could bring back to its core https://github.com/postcss/postcss/issues/477

I need to think about how cssnext can evolve to follow this changes. Maybe it should die and provide an .postcssrc has a replacement in a near future.

**Comment by kevinSuttle** [comment]
https://developer.mozilla.org/en-US/Add-ons/SDK/Guides/SDK_API_Lifecycle#Stability_Index maybe?

**Comment by jescalan** [comment]
👍 agreed with not including lower than level 2. The last thing we want is to ship out a feature only to have people rely on it then have it pulled later.

**Comment by MoOx** [comment]
@jonathantneal feel free to share update about your work on css-db here. I guess cssnext can become: preset-stage-0 (or 1?) or just include all stage and allow people to choose stage. Thoughts?

**Comment by danny-andrews** [comment]
Just found this discussion. I'm really excited to be able to use future css features with postcss the way I use future js features with babel!

> I guess cssnext can become: preset-stage-0 (or 1?) or just include all stage and allow people to choose stage. Thoughts?
@MoOx
I like the idea of including all stages and allowing people to choose the stage they want. Ultimately, I think it would be great if we had a monorepo like babel does with all the css-future transformations, and presets which bundle them based on stage. This will be a long way in the future, though.

**Comment by MoOx** [comment]
`postcss-cssnext` has been deprecated in favor or `postcss-preset-env`. Read more at https://moox.io/blog/deprecating-cssnext/
