### ISSUE TITLE
Add support for attribute selector case insensitive

### ISSUE THREAD

**Issue by MoOx** [MoOx/postcss-cssnext#111]
http://www.w3.org/TR/2013/WD-selectors4-20130502/#attribute-case

From a @ben-eb idea

> i had a brilliant, yet stupid idea for a postcss module - you know in CSS4 we will get [attr=test i] - which will match insensitively?
> well, you can write a module that converts that to [attr=test], [attr=Test], [attr=TEst], [attr=TESt], [attr=TEST], [attr=tEst] etc
> how genius is that?

**Comment by gjjones** [comment]
Am I wrong in thinking that this would expand to 2^n variations, where n=character length? It would be an opt-in with the "i" option, but this would get out of control quick.

Is this worth the potential pitfalls?

**Comment by ben-eb** [comment]
@gjjones Yep, which is why it's a stupid idea. But it could let people try out the new case-insensitive syntax in browsers that don't support it yet. :smile:

**Comment by Semigradsky** [comment]
@MoOx  Hey! I have created plugin: https://github.com/Semigradsky/postcss-attribute-case-insensitive :smile_cat:

**Comment by MoOx** [comment]
Feel free to make a PR for it ;)

**Comment by MoOx** [comment]
Closed by #306
