### ISSUE TITLE
Investigate for :root in media queries

### ISSUE THREAD

**Issue by MoOx** [MoOx/postcss-cssnext#115]
Ref https://github.com/postcss/postcss-custom-properties/issues/9#issuecomment-96322963

**Comment by larsenwork** [comment]
Any updates on this? I'd like to look into this but I've really used PostCSS the last half year so any pointers on how to approach this and pitfalls to be aware of would be great as I can see there has been multiple discussions about this in different issues.

**Comment by MoOx** [comment]
Everything I know is in the relevant issue mentioned above.

**Comment by MoOx** [comment]
`postcss-cssnext` has been deprecated in favor or `postcss-preset-env`. Read more at https://moox.io/blog/deprecating-cssnext/
