### ISSUE TITLE
Add a note for people that want to help

### ISSUE THREAD

**Issue by MoOx** [MoOx/postcss-cssnext#120]
Basically just a short explanation on how to help and a link to the "pr welcome" status

https://github.com/cssnext/cssnext/issues?q=is%3Aopen+is%3Aissue+label%3A%22status%3A+pr+welcome%22

**Comment by magsout** [comment]
After contributing, and why not make a tweet ?

**Comment by MoOx** [comment]
I want to add that in the futur revamped website :)

**Comment by magsout** [comment]
new website ? yeeah nice..

**Comment by MoOx** [comment]
Nobody is helping anyway...
