### ISSUE TITLE
❤︎ Who is using cssnext ?

### ISSUE THREAD

**Issue by MoOx** [MoOx/postcss-cssnext#128]
I am creating a page for the new website and would like to know who is using it (companies).

If you are interested, please fill the following out:
- Name: (correctly formatted)
- Homepage url: (homepage/primary entry point for users)
- Brand Guidelines/Licensing: (or anything we need to know before using your logo)
- Logo: (svg if possible, pngs over 500x200px with transparent backgrounds are also acceptable)

(ripped from babel)

**Comment by blittle** [comment]
@MoOx 

We moved entirely from SASS to cssnext.

Name: *Canopy*
Homepage url: https://www.canopytax.com
Brand Guidelines/Licensing: None currently
Logo: https://drive.google.com/a/canopytax.com/file/d/0B60grZQqYba0TG9KdlNhaDFVRTg/view?usp=sharing

**Comment by kud** [comment]
Name: Play TV
Homepage url: http://playtv.fr
Brand Guidelines/Licensing: None currently
Logo: http://m.playtv.fr/assets/images/logo.svg

**Comment by MoOx** [comment]
Great, thanks guys !
(I will wait for some others comments here before creating the page. I think a minimum of 5/10 consequent companies is mandatory to have a serious page)

**Comment by kud** [comment]
I agree. ;) Thank you anyway.

**Comment by magsout** [comment]
Name: Splitfire
Homepage url: http://splitfire.fr
Brand Guidelines/Licensing: None currently
Logo: https://dl.dropboxusercontent.com/u/92935009/logo_splitfire.png

**Comment by emmenko** [comment]
Name: SPHERE.IO
Homepage url: http://sphere.io/
Brand Guidelines/Licensing: http://sphere.io/assets/pdf/SPHEREIO-corporate-design-manual.pdf
Logo: http://sphere.io/assets/img/sphereio_logo.svg

Thanks :+1:

**Comment by karlcow** [comment]
Name: Webcompat
Homepage url: https://webcompat.com/
Brand Guidelines/Licensing: none
Logo: https://webcompat.com/favicon/favicon-196x196.png

**Comment by jxnblk** [comment]
Love what you're doing here on cssnext. If you feel like Basscss is relevant to this page here's the details:

Name: Basscss
Hompage url: http://basscss.com
Brand Guidelines/Licensing: ¯\\_(ツ)_/¯
Logo: https://github.com/basscss/logo/tree/master/images

**Comment by MoOx** [comment]
I will wait for 3 others to get a minimum of 9 "users".

**Comment by ai** [comment]
We picked plugins manually but it is a most of cssnext pack.

Name: Amplifr
Hompage url: http://amplifr.com/en
Brand Guidelines/Licensing: None currently
Logo: https://amplifr.com/logo.png

**Comment by t32k** [comment]
We love cssnext :heart:

Name: Kaizen Platform, Inc.
Hompage url: https://kaizenplatform.com/
Brand Guidelines/Licensing: None currently
Logo: http://bit.ly/1Ubb08T

**Comment by jedmao** [comment]
Name: HauteLook
Homepage URL: http://hautelook.com/
Brand Guidelines/Licensing: I'm told it would be fine to represent HauteLook here.

[![hautelook-logo](https://cloud.githubusercontent.com/assets/1058243/9015429/84557c52-378e-11e5-8638-da621d3e90a2.png)](http://hautelook.com/)

**Comment by stevenvachon** [comment]
I still use Less.js because of principle. All of its functionality is either already in CSS specs or is available through postcss plugins, but documentation is scattered and having a `*.css` file implies that it's standard CSS. Things like extending and nested media queries are not part of any spec.

**Comment by stevenvachon** [comment]
I realize now the purpose of this thread. Oops. Still, though, I'm curious what others think of my comment.

**Comment by jonathanKingston** [comment]
@stevenvachon Pretty sure nested media is supported etc and extension was defined in a Tab Atkins spec (he is super busy and stretched loads etc) but yeah it's happening.
Mostly I find the practices of preprocessing can be redone in native CSS, especially when real custom property support is possible.
I need to write up how we wrote our site at some point to reduce the need of things like macros etc.

If interested:

Name: Cyber AMI
Homepage url: https://www.cyber-ami.com/
Brand Guidelines/Licensing: Not a clue. Assume Oracle or something :+1: 
Logo: ![Cyber AMI](https://www.cyber-ami.com/images/logo-cyber-ami.svg)

**Comment by stevenvachon** [comment]
@jonathanKingston I didn't mean nesting a `@media` within another `@media`, but instead this:
```css
element {
  @media (stuff) {
    property: value;
  }
}
```
I'm pretty sure that's not valid CSS, but it is very useful.

Very interesting about `@extend`: https://tabatkins.github.io/specs/css-extend-rule/#extend-rule

**Comment by asifshirazi** [comment]
Name: colwiz
Homepage url: https://www.colwiz.com
Brand Guidelines/Licensing: None currently
Logo: https://cdn.colwiz.com/static/images/login_images/colwiz_logo_1024.png

**Comment by msisto** [comment]
Those Basscss buttons look exactly like Semantic UI

**Comment by rafaelrinaldi** [comment]
Name: Work & Co
Homepage url: https://work.co
Brand Guidelines/Licensing: None currently
Logo: http://work.co/images/logos/logo-fill-red.png

**Comment by renestalder** [comment]
Name: whatwedo
Homepage url: https://whatwedo.ch
Brand Guidelines/Licensing: None currently
Logo: [whatwedo-logo-RGB.svg.zip](https://github.com/MoOx/postcss-cssnext/files/212743/whatwedo-logo-RGB.svg.zip)

**Comment by ai** [comment]
Wikipedia

**Comment by MoOx** [comment]
`postcss-cssnext` has been deprecated in favor or `postcss-preset-env`. Read more at https://moox.io/blog/deprecating-cssnext/
