### ISSUE TITLE
should have a compress option

### ISSUE THREAD

**Issue by MoOx** [MoOx/postcss-cssnext#14]

**Comment by perrin4869** [comment]
Stumbled into here while trying to get `cssnext` and `cssnano` to work together, since it `cssnext` kept warning me about multiple `autoprefixer` usage. Should compression really under the scope of `cssnext`?

**Comment by MoOx** [comment]
cssnext does not handle compression since it has been changed to postcss-cssnext.
We should do something about the warning tho even if I have no idea how to handle that yet poke @ben-eb.

**Comment by ben-eb** [comment]
Does it work if you disable autoprefixer in cssnano? e.g. via this options object;

```js
{
  autoprefixer: false
}
```

**Comment by perrin4869** [comment]
yeah, that's the solution I went with for now actually :)
I guess `autoprefixer` will be turned off on `cssnano@4.0` with `safe: true` then?
`compress` option will be removed from the next `cssnext` version?

**Comment by ben-eb** [comment]
I am thinking of making it opt-in for version 4, so it would be something that the user would have to configure themselves. That way I don't have to filter the plugins list for duplicate autoprefixer instances.

**Comment by perrin4869** [comment]
@ben-eb I think that is the best solution, since most people will probably be using `autoprefixer` for adding vendor prefixes in the first place, and they don't want them to be removed

**Comment by MoOx** [comment]
@perrin4869 there is no more "compress" option. See http://cssnext.io/postcss/
