### ISSUE TITLE
Reduce overlapping functionality between cssnext & cssnano

### ISSUE THREAD

**Issue by ben-eb** [MoOx/postcss-cssnext#156]
It would be good for both of our modules to be able to disable processors based on what has already been transformed. cssnext already disables postcss-calc before the AST goes through to cssnano, but we can do more.

For example, I can detect that automatically by analysing the processor instance for postcss-calc and disabling it silently; same with postcss-pseudoelements.

It would be nice if you could disable postcss-rebeccapurple when cssnano is enabled as it is already converted to hex by postcss-colormin. :smile:

**Comment by ben-eb** [comment]
This commit adds support for detecting previous processors: https://github.com/ben-eb/cssnano/commit/aa92416d0413a2e84b12b03918f2498b6568806e

**Comment by MoOx** [comment]
Is this ok since v2 ?

**Comment by ben-eb** [comment]
On my end yes. :wink:

> It would be nice if you could disable postcss-rebeccapurple when cssnano is enabled as it is already converted to hex by postcss-colormin

**Comment by MoOx** [comment]
I need to check first that color function can handle it.

**Comment by ben-eb** [comment]
Any movement on this? Is it relevant anymore since postcss-cssnext?

**Comment by MoOx** [comment]
I guess it's still relevant.

**Comment by ben-eb** [comment]
I'm happy to close this, v4's architecture means that detection of duplication will be trickier for other modules outside cssnano as it won't bundle any PostCSS plugins (save for autoprefixer).
