### ISSUE TITLE
Move code in cssnext repo

### ISSUE THREAD

**Issue by MoOx** [MoOx/postcss-cssnext#16]
In order to make the maintenance of the postss plugin package / cli package / docs, I want to keep all npm packages in the same repo. So I will refactor cssnext repo in order to handle that this way. Like babel does https://github.com/babel/babel/tree/112c24a3d3e22be621265ad34aff39a842c3bf7b/packages 
This will also keep watchers and stargazers :)

**Comment by joaocunha** [comment]
:+1:

**Comment by MoOx** [comment]
https://github.com/babel/babel/blob/a26186cf21439ef953411363e7e76b946b6cdb98/doc/design/monorepo.md

**Comment by MoOx** [comment]
WIP https://github.com/MoOx/cssnext/pull/238
