### ISSUE TITLE
Add Conic Gradient support

### ISSUE THREAD

**Issue by ai** [MoOx/postcss-cssnext#161]
Conic gradients is a new draft promototed without any implementation, but with SVG polyfill.

@jonathantneal rewrote polyfill to PostCSS: https://github.com/jonathantneal/postcss-conic-gradient/issues

But the main question is, how to install Cairo.

**Comment by jonathantneal** [comment]
With [brew](http://brew.sh/), this can be as simple as:

```sh
brew install cairo
```

There are [installation instructions available](https://github.com/Automattic/node-canvas/wiki), and those instructions [worked well with travis](https://github.com/jonathantneal/postcss-conic-gradient/blob/master/.travis.yml#L3).

**Comment by ai** [comment]
It makes all cssnext installation process more complicated. Maybe we can remove Cairdo dependency? For example by creating SVG XML by hands?

**Comment by jonathantneal** [comment]
Maybe. Right now, Cairdo is used to [generate the Canvas](https://github.com/jonathantneal/postcss-conic-gradient/blob/master/index.js#L20) which is then used to [generate the PNG](https://github.com/jonathantneal/postcss-conic-gradient/blob/master/index.js#L122). The original did something like `document.createElement('canvas')`.

**Comment by ai** [comment]
Why PNG and not origin vector format?

**Comment by jonathantneal** [comment]
It [may be possible](http://midiwebconcept.free.fr/Demos/degradeconique.htm), but this would require an entire redesign of the polyfill.

**Comment by MoOx** [comment]
This is totally cool. That said, the cairo deps seems overkill :/
How does the polyfill behave if cairo is not availabe (error or simple message) ?
What would be cool is that the plugin might not say anything until someone really try to use it. And if cairo is not available, a simple postcss warning will be really cool instead of a breaking error. If the plugin might behave like this, I would be really happy to integrate this feature !

**Comment by ai** [comment]
I think PNG solution is good only for first implementation. But maybe we should wait for pure SVG implementation for cssnext without Cairo dependency?

**Comment by bloodyowl** [comment]
in my experience, projects requiring cairo have always been a pain to install and run

**Comment by MoOx** [comment]
We will probably wait for (or do) a cairo free version then.

**Comment by MoOx** [comment]
`postcss-cssnext` has been deprecated in favor or `postcss-preset-env`. Read more at https://moox.io/blog/deprecating-cssnext/
