### ISSUE TITLE
Some features needs to be deactivated without using caniuse-db

### ISSUE THREAD

**Issue by lydell** [MoOx/postcss-cssnext#164]
``` sh
$ mkdir cssnext-test
$ cd cssnext-test/
$ npm i cssnext
# snip
cssnext@1.7.1 node_modules/cssnext
# snip
$ echo 'a { filter: drop-shadow(0 0 5px black) }'>test.css
$ cssnext test.css
a { filter: url('data:image/svg+xml;charset=utf-8,<svg xmlns="http://www.w3.org/2000/svg"><filter id="filter"><feGaussianBlur in="SourceAlpha" stdDeviation="5" /><feOffset dx="1" dy="1" result="offsetblur" /><feFlood flood-color="rgba(0,0,0,1)" /><feComposite in2="offsetblur" operator="in" /><feMerge><feMergeNode /><feMergeNode in="SourceGraphic" /></feMerge></filter></svg>#filter'); -webkit-filter: drop-shadow(0 0 5px black); filter: drop-shadow(0 0 5px black) }
$ npm i autoprefixer
autoprefixer@5.2.0 node_modules/autoprefixer
├── postcss@4.1.13 (js-base64@2.1.8, es6-promise@2.3.0, source-map@0.4.2)
├── autoprefixer-core@5.2.1 (num2fraction@1.1.0, browserslist@0.4.0, caniuse-db@1.0.30000215)
└── fs-extra@0.18.4 (jsonfile@2.1.2, graceful-fs@3.0.8, rimraf@2.4.0)
$ autoprefixer <test.css
Autoprefixer CLI is deprecated. Use postcss-cli instead.
a { -webkit-filter: drop-shadow(0 0 5px black); filter: drop-shadow(0 0 5px black) }
```

Why are the `cssnext` and `autoprefixer` results different? I’d expect them to be equal.

**Comment by lydell** [comment]
Actually, it seems as if the entire “browsers” option is ignored:

```sh
$ cssnext test.css -b 'Firefox >= 38'
a { filter: url('data:image/svg+xml;charset=utf-8,<svg xmlns="http://www.w3.org/2000/svg"><filter id="filter"><feGaussianBlur in="SourceAlpha" stdDeviation="5" /><feOffset dx="1" dy="1" result="offsetblur" /><feFlood flood-color="rgba(0,0,0,1)" /><feComposite in2="offsetblur" operator="in" /><feMerge><feMergeNode /><feMergeNode in="SourceGraphic" /></feMerge></filter></svg>#filter'); filter: drop-shadow(0 0 5px black) }
```

**Comment by lydell** [comment]
I can’t get the inlined SVG output with autoprefixer.

```
$ autoprefixer <test.css -b '> 0%'
Autoprefixer CLI is deprecated. Use postcss-cli instead.
a { -webkit-filter: drop-shadow(0 0 5px black); filter: drop-shadow(0 0 5px black) }
```

Is that done by some other plugin used by cssnext? If so I’ve just been confused all the time, and the real issue is that the “browsers” option should control more than it does.

**Comment by ben-eb** [comment]
It might be worth being able to set a `browsers` option in pleeease-filters :smile:

**Comment by lydell** [comment]
Good idea.

**Comment by MoOx** [comment]
pleeease-filters is not deactivated for now. I need to add manual tests in the feature activation map.
It's not really a bug, but we should definitely handle that.

**Comment by MoOx** [comment]
Some plugins need to not even be added in the pipe.

**Comment by lydell** [comment]
Yes, it is not a bug. But it is really confusing. I consider myself comfortable and familiar with postcss (I’ve even contributed code to it), but still I fell into this trap :)

**Comment by ben-eb** [comment]
I like the idea of having a global `browsers` option which is passed around to all relevant plugins. It's something that I plan to add to cssnano 3, where `browsers` will be used by both autoprefixer and this css hacks processor that's in the works.

**Comment by MoOx** [comment]
I think some "stupid" plugin that does just one thing should not add browserlist. Only tricky plugin like autoprefixer, pixrem or this one.
I will use browserslist to detect some browsers usage (in this case firefox < 35) and add a new behavior to the feature activation map so we can define a range a browser to define when a plugin is useless.

**Comment by MoOx** [comment]
`postcss-cssnext` has been deprecated in favor or `postcss-preset-env`. Read more at https://moox.io/blog/deprecating-cssnext/
