### ISSUE TITLE
Adding background-blend-mode support

### ISSUE THREAD

**Issue by Seanathon** [MoOx/postcss-cssnext#222]
Would getting this to work on all browsers even be possible using CSSNext? Currently IE doesn't support it at all and Safari doesn't work with color, hue, multiply, etc.

**Comment by MoOx** [comment]
Not sure if that is possible.

**Comment by niutech** [comment]
How about [SVG filters](http://www.jeromecukier.net/blog/2015/05/05/blending-mode-and-svg/)?

**Comment by dbox** [comment]
@niutech that is awesome!

**Comment by niutech** [comment]
You can use [feBlend](http://apike.ca/prog_svg_filter_feBlend.html) filter in IE10+.

**Comment by dbox** [comment]
Whoahhh.Great!

**Comment by MoOx** [comment]
`postcss-cssnext` has been deprecated in favor or `postcss-preset-env`. Read more at https://moox.io/blog/deprecating-cssnext/
