### ISSUE TITLE
Nested Media Queries

### ISSUE THREAD

**Issue by realph** [MoOx/postcss-cssnext#224]
Is it possible to have nested media queries in your css, just like sass?

```sass
.navbar.compact {
  width: auto;

  @media (--breakpoint-md) {
    width: var(--navbar-compact-width-md);
  }

  @media (--breakpoint-lg) {
    width: var(--navbar-compact-width-lg);
  }
}
```

Any help is appreciated. Thanks in advance!

**Comment by Macxim** [comment]
See https://github.com/cssnext/cssnext/issues/30

**Comment by realph** [comment]
@Macxim Not sure I understand that thread. Can I do the above? They seem to be nesting media queries inside of other media queries, where as I want to nest media queries inside of CSS declarations.

**Comment by Macxim** [comment]
@realph Alright, my bad. I read too fast.
In this case, it would be like CSS nesting discussed here https://github.com/cssnext/cssnext/issues/80.

**Comment by MoOx** [comment]
For you information, this is currently working thank to postcss-nesting.

Example:

```
.navbar.compact {
  width: auto;

  @media (width < 50em) {
    width: 20em;
  }
}
```

will give

```css
.navbar.compact {
  width: auto
}

  @media (max-width: 49.999em) {

  .navbar.compact {
    width: 20em
  }
  }
```

**Comment by Macxim** [comment]
Nice! :+1:
