### ISSUE TITLE
Confused on how to enable sourcemaps migrating from cssnext 

### ISSUE THREAD

**Issue by 0x80** [MoOx/postcss-cssnext#243]
I read the migration docs and everything else I could find but I still don't get where I should enable sourcemaps in my webpack config? :/

Here's what I have so far:

```javascript
 postcss: function (webpack) {
    return [
      require('autoprefixer')({
        browsers: 'last 2 versions',
        remove: false // faster if not processing legacy css
      }),
      require('postcss-import')({
        path: path.join(__dirname, 'app'),
        addDependencyTo: webpack, // for HMR
        glob: true
      }),
      require('postcss-url')(),
      require('postcss-cssnext')(),
      require('postcss-mixins')(),
      require('postcss-nested')(),
      require('postcss-browser-reporter')(),
      require('postcss-reporter')()
    ]
  },
```

**Comment by MoOx** [comment]
This is not something that's will be handled here.
This is more a webpack config question.
It seems that this can be enable with css-loader https://github.com/webpack/css-loader#sourcemaps
(I don't use sourcemap so I am not sure).
Feel free to reopen if that does not help.

**Comment by 0x80** [comment]
Ok thanks for the quick reply!
