### ISSUE TITLE
WTF WHY DO I NEED POSTCSS

### ISSUE THREAD

**Issue by mxstbr** [MoOx/postcss-cssnext#244]
I JUST WANT THE CSS4 SYNTAX WHY DO I HAVE TO INCLUDE A FUCKING PREPROCESSOR NOBODY NEEDS WHAT THE FUCK I CAN CODE BETTER THAN YOU WHY CANT YOU LEAVE THIS ALONE YOU BETTER RELEASE STANDALONE CSSNEXT SOON OR ILL TELL MY MOM 

----

> This is just a joke, please don't take it seriously. I ❤ @MoOx and cssnext and PostCSS. See [this tweet] (https://twitter.com/MoOx/status/685519491594334208?s=09)

**Comment by MoOx** [comment]
![action-kingsman](https://cloud.githubusercontent.com/assets/157534/12205343/57abbb46-b63a-11e5-8351-08e4c910320e.gif)

**Comment by MoOx** [comment]
:D

**Comment by mxstbr** [comment]
😂 that gif is 👌

**Comment by magsout** [comment]
👌
