### ISSUE TITLE
String interpolation

### ISSUE THREAD

**Issue by yordis** [MoOx/postcss-cssnext#248]
I have this code snippet and doesn't work for me. Any thoughts.
```
:root {
  --color: red;

  --google-font-name: 'Lato';
  --google-font-sizes: '400,700,400italic,700italic';
  --google-subset: 'latin';
  --google-font-request: 'var(--google-font-name):var(--google-font-sizes)&subset=var(--google-subset)';
  --google-font-url: 'https://fonts.googleapis.com/css?family=var(--google-font-request)'
}

@import url(var(--google-font-url))
```

**Comment by MoOx** [comment]
Does not match CSS spec.
var() can only be used for property values, as a real function. Not in a string.
In your case I think your are just doing some over-engineering :/

**Comment by yordis** [comment]
@MoOx sorry for my lack of experience with the spec. Thank you very much!

**Comment by MoOx** [comment]
No problem. Next time, use [the gitter chat](https://gitter.im/MoOx/postcss-cssnext) for this kind of question.
