### ISSUE TITLE
How do I configure autoprefixer when using webpack?

### ISSUE THREAD

**Issue by F21** [MoOx/postcss-cssnext#249]
I have cssnext required like so in my webpack config:

```javascript
const cssnext = require('postcss-cssnext');
```

Then I ask the postcss-loader to use it:

```javascript
postcss: function () {
   return [cssnext({autoprefixer: {browsers: "ie >= 7"}})];
 }
```

Autoprefixer does not appear to be using the browserlist I am passing in.

This is the snippet of CSS I am using to test:

```css
background: linear-gradient(to bottom, #1e5799 0%,#2989d8 50%,#207cca 51%,#7db9e8 100%);
```

Even though browsers is set to `ie >=7`, it's not adding this entry:

```css
filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#1e5799', endColorstr='#7db9e8',GradientType=0 );
```

I also tried different configuration formats:

```javascript
{browsers: "ie >= 7"}

{browsers: ["ie >= 7"]}
```

It would be immensely helpful if this was better documented.

**Comment by F21** [comment]
After experimenting with http://autoprefixer.github.io/, I discovered that autoprefixer does not add `filters`.

For the record, the configuration to set up autoprefixer is `{browsers: "ie >= 11, ..."}`

**Comment by MoOx** [comment]
For you information, postcss-cssnext have a browser option that is sent to autoprefixer http://cssnext.io/usage/#browsers
