### ISSUE TITLE
Pass options to autoprefixer

### ISSUE THREAD

**Issue by F21** [MoOx/postcss-cssnext#250]
I am using cssnext with the postcss loader with webpack.

I want to turn off grid support in autoprefixer:

```javascript
autoprefixer({ grid: false });
```

It would be really awesome if cssnext can take an object of autoprefixer options and pass that to autoprefixer.

**Comment by F21** [comment]
Apply it to the autoprefixer feature like so:

```javascript
cssnext({
    feature: {
        autoprefixer: {
            grid: false
        }
    }
});
```

**Comment by baribadamshin** [comment]
Right way to define options is use feature**s** instead of feature. 
Example

```
cssnext({
    features: {
        autoprefixer: {
            grid: false
        }
    }
});
```
