### ISSUE TITLE
Make it more visible that cssnext is a plugin pack / a preset

### ISSUE THREAD

**Issue by MoOx** [MoOx/postcss-cssnext#251]
Should we use "plugin pack" or "preset" like Babel? poke @ai

**Comment by ai** [comment]
Plugin pack is a simplier and cleaner word for preset. But preset is more popular. So I have no idea.

**Comment by jedmao** [comment]
I prefer "plugin pack" because it's more clear what's going on. Preset could mean a number of different things.

**Comment by stevenvachon** [comment]
How about
```
cssnext is a plugin pack (or "preset")…
```

**Comment by piotr-cz** [comment]
Another world used in php world is _metapackage_.
But anything would be helpful

**Comment by MoOx** [comment]
`postcss-cssnext` has been deprecated in favor or `postcss-preset-env`. Read more at https://moox.io/blog/deprecating-cssnext/
