### ISSUE TITLE
Cannot use properties from imported files

### ISSUE THREAD

**Issue by aroc** [MoOx/postcss-cssnext#259]
If I have some custom properties defined in an imported file, such as:

```
/*properties.css*/
:root {
  --font-family: 'Gotham Rounded SSm A', 'Gotham Rounded SSm B', 'Helvetica Neue', Helvetica, Arial, sans-serif;
}
```

I cannot use them inside other files where they are imported, like this:

```
@import '../properties.css'

p {
  font-family: var(--font-family);
}
```

I get the following error:
` variable '--font-family' is undefined and used without a fallback`

I apologize in advance if this is a usage error on my part. I searched through the issues and re-read the docs several times but couldn't find an answer to this.

**Comment by MoOx** [comment]
No problem. Prefer the gitter support chat for this kind of question.
Are you using postcss-import in addition to postcss-cssnext? If not that will help :)
