### ISSUE TITLE
Combine custom media queries

### ISSUE THREAD

**Issue by patrickpietens** [MoOx/postcss-cssnext#261]
Having the following set of custom queries:

```
@custom-media --small (width <= 30em);
@custom-media --normal (width >= 30.01em) and (width <= 45em);
@custom-media --wide (width >= 45.01em) and (width <= 55em);
@custom-media --wider (width >= 55.01em);
```

Is it possible to combine them for example like this:

```
@media (--small) and (--normal) {
}
```

or 

```
@media (--small and --normal) {
}
```

Thnx

**Comment by MoOx** [comment]
I think  what you want to do is

```css
@media (--small), (--normal) {
}
```

Just [try on the playground](http://cssnext.io/playground/) and checkout the output.

**Comment by patrickpietens** [comment]
Boom!!! Works like a charm.
Thnx for your superfast answer <3
