### ISSUE TITLE
[FAQ] Variables don't work inside @media queries 

### ISSUE THREAD

**Issue by pvijeh** [MoOx/postcss-cssnext#262]
I am trying to use a variable inside of a media query like this: 

```
@media (width <= var(--screen-md-min)) {
    background-color: var(--brand-purple-dark);    
}
```

but I get this message in the console: 

Missing @custom-media definition for '--screen-md-min'. The entire rule has been removed from the output.

**Comment by MoOx** [comment]
See https://github.com/MoOx/postcss-cssnext/issues/253

**Comment by MoOx** [comment]
I will add this into a FAQ since every body is asking for this.

**Comment by MoOx** [comment]
`postcss-cssnext` has been deprecated in favor or `postcss-preset-env`. Read more at https://moox.io/blog/deprecating-cssnext/
