### ISSUE TITLE
Question about browserlist configuration

### ISSUE THREAD

**Issue by rafaelrinaldi** [MoOx/postcss-cssnext#263]
Currently it's kinda confusing to me the best way to pass in the [`browserlist`](https://github.com/ai/browserslist) configuration. As far as I know, this is being used by [Autoprefixer](https://github.com/postcss/autoprefixer) and [pixrem](https://github.com/robwierzbowski/node-pixrem).

Given that I'm using PostCSS CLI, and a JSON configuration file to specify the rules, how is the best way  to pass in the browser information? Shouldn't it be possible by just looking for an `autoprefixer` key on the configuration object? Should I use one key per plugin?

Ps.: Sorry if it's a dumb question, still getting used to the ecosystem.

**Comment by MoOx** [comment]
cssnext have its own "browsers" option, which is propagated to autoprefixer. You can also use browserlistrc file that will be used by all thoses plugins.
See #174 for pixrem (to be done).

**Comment by rafaelrinaldi** [comment]
@MoOx Thanks a lot. Do you want me to send a PR making this crystal clear on the docs?

**Comment by MoOx** [comment]
Sure. Btw, implementing #174 should be really quick, just need to copy the method used for autoprefixer :)

**Comment by rafaelrinaldi** [comment]
@MoOx Would you like me to go ahead and try to make a PR for both? :)

**Comment by MoOx** [comment]
Just go <3.
Ping me on gitter https://gitter.im/MoOx/postcss-cssnext if you need a hand.

**Comment by rafaelrinaldi** [comment]
@MoOx 

![hell yes](https://cldup.com/Za4u_CCVN6.gif)

**Comment by MoOx** [comment]
Closed, see #264.
