### ISSUE TITLE
how do I turn off autoprefixing "grid" rule?

### ISSUE THREAD

**Issue by t0lkman** [MoOx/postcss-cssnext#267]
<pre>
postcss: function (webpack) {
    return [
      require("postcss-import")({ addDependencyTo: webpack }),
      require("postcss-cssnext")({
        browsers: ['last 2 versions'],
        feature: {
          grid: false
        }
      }),
      require("postcss-reporter")()
    ]
  }
</pre>
it looks like `grid: false` being ignored

**Comment by MoOx** [comment]
```js
postcss: function (webpack) {
    return [
      require("postcss-import")({ addDependencyTo: webpack }),
      require("postcss-cssnext")({
        browsers: ['last 2 versions'],
        feature: {
          autoprefixer: { grid: false }
        }
      }),
      require("postcss-reporter")()
    ]
  }
```

**Comment by swrobel** [comment]
If anyone else comes across this, I believe the correct config should be as follows:

```js
features: {
  autoprefixer: { grid: false }
}
```

note `features` instead of `feature`. Also, I believe grid is disabled by default, so you really only need this config if you want to enable grid prefixing (like I do), which would be `grid: true` instead.
