### ISSUE TITLE
not correct work autoprefix with @keyframes

### ISSUE THREAD

**Issue by serGlazkov** [MoOx/postcss-cssnext#268]
i call `cssnext` with some browsers parameter
```
require('postcss-cssnext')({
    browsers: ['last 2 versions', 'Chrome >= 42', 'Firefox >= 38', 'iOS >= 7', 'Android >= 4']
}),
```
and I have in my css `@keyframes` animation
in result cssnext not generate `-webkit` prefix to keyframes for iOS Safari 8.4

if i use autoprefixer plugin it work great

**Comment by MoOx** [comment]
What version of the plugin are you using please?

**Comment by serGlazkov** [comment]
"postcss-cssnext": "=2.5.1"

**Comment by MoOx** [comment]
Can you provide some css as well please?

**Comment by serGlazkov** [comment]
sorry, it's my error, i use this plugins for postcss
```
var processors = [
        require('precss'),
        require('postcss-short'),
        require('postcss-cssnext')({
            browsers: ['last 2 versions', 'Chrome >= 42', 'Firefox >= 38', 'iOS >= 7', 'Android >= 4']
        }),
        require('postcss-animation'),
        require('lost'), 
        require('css-mqpacker')
    ];
```
and i connect postcss-animation after postcss-cssnext, need to change position :)
