### ISSUE TITLE
Duplicate warning when used with `postcss-url`

### ISSUE THREAD

**Issue by shannonmoeller** [MoOx/postcss-cssnext#269]
For some reason, postcss-cssnext always logs the `warnForDuplicates` message for `autoprefixer` when used with [`postcss-url`](https://github.com/postcss/postcss-url). It doesn't matter which plugin is registered first, and setting `warnForDuplicates` to `false` does not prevent the message from displaying.

 This is my full use case:

```js
const pipeline = postcss([
    postcssImport(),
    postcssApply(),
    postcssUrl(),
    postcssNext({ warnForDuplicates: false }),
    postcssNano({ autoprefixer: false })
]);
```

But even when you drop nano, the message still shows and order doesn't seem to matter. Note that in this case I'm not even using `postcss-import`, but the error still displays.

```js
const pipeline = postcss([
    postcssApply()
    postcssNext({ warnForDuplicates: false }),
    postcssUrl()
]);
```

This doesn't make any sense to me, because as far as I can tell, `postcss-url` doesn't include `autoprefixer` anywhere.

![image](https://cloud.githubusercontent.com/assets/155164/13924554/2f52fdc6-ef5b-11e5-94fd-531916f58465.png)

**Comment by MoOx** [comment]
The autoprefixer thing should be adjusted if registered from cssnano (@ben-eb any idea how to do that?)
Except this case it looks like a bug, will take a look.

**Comment by ben-eb** [comment]
I wrote this but it seems like it causes more problems than it solves...

https://github.com/postcss/postcss-filter-plugins/blob/master/README.md

**Comment by MoOx** [comment]
@shannonmoeller are you sure that in your last snippet (without cssnano) it trigger the autoprefixer warning with a fresh runtime?

**Comment by shannonmoeller** [comment]
I'll verify that with a reduced test case this evening.

**Comment by shannonmoeller** [comment]
I setup a fresh project with the above plugins and wasn't able to reproduce the issue. However, I updated my other project to the latest of everything and it's still happening there. Seems to be a weird side-effect issue. Still digging.

**Comment by shannonmoeller** [comment]
Well, this is embarrassing. Finally found the root cause of my issue. My import statement for postcss-url was accidentally pointed at postcss-cssnext, so cssnext was getting run twice, thus the error. So sorry for wasting your time!
