### ISSUE TITLE
`features` object does not guarantee property order

### ISSUE THREAD

**Issue by wc-matteo** [MoOx/postcss-cssnext#282]
if the order matters, shouldn't it be a [Map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map)?

**Comment by MoOx** [comment]
Yeah that's a good idea. PR welcome :)

**Comment by bloodyowl** [comment]
what node support does the package officially support?

**Comment by yordis** [comment]
@wc-matteo Sorry but I don't get why should be a Map. Can you explain me please?

**Comment by MoOx** [comment]
Because http://stackoverflow.com/questions/5525795/does-javascript-guarantee-object-property-order

**Comment by MoOx** [comment]
`postcss-cssnext` has been deprecated in favor or `postcss-preset-env`. Read more at https://moox.io/blog/deprecating-cssnext/
