### ISSUE TITLE
Is it possible to keep CSS custom properties in output?

### ISSUE THREAD

**Issue by 0x80** [MoOx/postcss-cssnext#283]
For a project I'm targeting only browsers that support custom properties, so I want to keep them in the output. It is possible to bypass the transpiling of those?

**Comment by MoOx** [comment]
You can use the `browser` option http://cssnext.io/usage/#browsers to scope the browsers you want. If caniuse data are correct, you should not have custom props transformed.
Keep in mind that you won't be able to mix transformations (eg: use custom props in color() functions).

**Comment by 0x80** [comment]
👍  I can confirm that it works. Caniuse reports 59.76% and setting the browser setting to > 60% keeps the variables in tact.

Thanks for the warning, I will have to be careful with that. But I assume the color functions are also part of an official CSS proposal?

**Comment by MoOx** [comment]
Yeah everything is part of (somehow) official CSS draft (or proposal by someone serious).
