### ISSUE TITLE
Quantity queries

### ISSUE THREAD

**Issue by kevinSuttle** [MoOx/postcss-cssnext#284]
https://github.com/pascalduez/postcss-quantity-queries @pascalduez, do you think this plugin is stable enough to be included?

**Comment by MoOx** [comment]
Is there any specification for this? If not this is not relevant for cssnext.

**Comment by kevinSuttle** [comment]
Hm. Doesn't seem to be. I assumed there was.

**Comment by ben-eb** [comment]
From the readme;

> This plugin is derived from the Sass [Quantity Queries mixins](https://github.com/danielguillan/quantity-queries) by Daniel Guillan.

https://github.com/pascalduez/postcss-quantity-queries#postcss-quantity-queries

Suggest to close. 😄
