### ISSUE TITLE
will-change plugin?

### ISSUE THREAD

**Issue by kevinSuttle** [MoOx/postcss-cssnext#288]
https://github.com/postcss/postcss-will-change @ai is this stable enough to include?

**Comment by ai** [comment]
I think we should include it. But @MoOx afraid `backface-visibility` insertion there. I think it is rare condition.

**Comment by kevinSuttle** [comment]
@MoOx Thoughts?

**Comment by MoOx** [comment]
Already discussed here #70, this is too dangerous. cssnext is dangerous enough ;)
