### ISSUE TITLE
Add the PostCSS Transform Shortcut plugin

### ISSUE THREAD

**Issue by Rowno** [MoOx/postcss-cssnext#290]
[PostCSS Transform Shortcut](https://github.com/jonathantneal/postcss-transform-shortcut) adds support for the new shorthand transform properties from the [CSS Transform Module Level 2 Specification](https://drafts.csswg.org/css-transforms-2/).

**Comment by MoOx** [comment]
Sorry but the caveat is too dangerous https://github.com/jonathantneal/postcss-transform-shortcut#caveat
