### ISSUE TITLE
Autoprefixer listed as a duplicate plugin by warnForDuplicates

### ISSUE THREAD

**Issue by PierrickGT** [MoOx/postcss-cssnext#292]
I've discovered today that the setup of CssNext changed and decided to update my Gulp setup.

So I've installed the necessary plugins and everything seems to work, except for this warning I get in the console when I build my project.

<img width="1275" alt="capture d ecran 2016-06-29 a 10 36 19" src="https://cloud.githubusercontent.com/assets/2401738/16446041/f0698f6a-3de5-11e6-9db6-e068a51fc6de.png">

Since it looks like Autoprefixer is duplicated, I've decided to uninstall it with the command

`npm uninstall -D autoprefixer` 

But by doing so, I can't build my project anymore cause it can't find autoprefixer...

<img width="420" alt="capture d ecran 2016-06-29 a 10 44 21" src="https://cloud.githubusercontent.com/assets/2401738/16446148/7cb04a54-3de6-11e6-9a05-25e2af46b1ab.png">

I guess it's just a wrong warning message but I want to make sure I've installed things correctly and that's why I open this issue. Here is my Gulp configuration :

```
// PostCSS Plugins
var cssnext = require('postcss-cssnext'),
precss = require('precss'),
assets  = require('postcss-assets'),
cssnano = require('cssnano'),
browserReporter = require("postcss-browser-reporter"),
reporter = require("postcss-reporter");

gulp.task('css', function() {
  var processors = [precss, cssnext, assets({
    basePath: 'public/',
    loadPaths: ['assets/images/**']
  }), browserReporter, reporter, cssnano({zindex: false})];
  return gulp.src('./source/css/style.css')
  .pipe($.sourcemaps.init())
  .pipe($.postcss(processors))
  .pipe($.sourcemaps.write('.'))
  .pipe(gulp.dest('./public/assets/stylesheets'))
  .pipe(browserSync.stream());
});
```

**Comment by MoOx** [comment]
By uninstalling autoprefixer, you potentially remove a dep installed by a peer (eg: if you use npm 3, postcss-cssnext will install autoprefixer at the same level). cssnano is using autoprefixer too, that's why you are getting this warning. So you can ignore this warning (by disabling autoprefixer in cssnano options).
