### ISSUE TITLE
@custom-media pulled from Media Queries Lvl.4 W3C Working Draft

### ISSUE THREAD

**Issue by jasonhale** [MoOx/postcss-cssnext#294]
Noticed [W3C's working draft of Media Queries Level 4](https://drafts.csswg.org/mediaqueries/) dated today (7-7-2016) no longer has notice of the @custom-media property (previous version [here](https://www.w3.org/TR/2016/WD-mediaqueries-4-20160126/#custom-mq)).
Will this affect cssnext and it's inclusion of the postcss-custom-media plugin?

**Comment by MoOx** [comment]
@jasonhale it can be.
Did you find any explanation in mailing list or something like that?
Maybe @tabatkins can give us some explanations?

**Comment by jasonhale** [comment]
Looking through CSSWG notes, looks like that feature got moved to [Level 5](https://www.w3.org/blog/CSS/2016/06/23/minutes-telecon-289/) - though haven't any issue specifically yet.  Apologies for knee-jerk question without investigation.
Since they are moved from the current level to a future level, and no timeline that I could see, I'd still be interested to hear if it would alter cssnext as it stands currently.

**Comment by MoOx** [comment]
For now there is no real rules. Any serious draft or proposal can be in cssnext (for example mixins via apply are [a proposal](https://tabatkins.github.io/specs/css-apply-rule)).

**Comment by lmaze** [comment]
Any news about #100 ? It could be really interesting to enable or disable features according to their level of stability :)

**Comment by MoOx** [comment]
As you can see nothing as been done. Contributions are welcome :)

**Comment by kevinSuttle** [comment]
https://github.com/w3c/csswg-drafts/issues/493

**Comment by MoOx** [comment]
Closing in favor of #100
