### ISSUE TITLE
Plugin versions

### ISSUE THREAD

**Issue by langri-sha** [MoOx/postcss-cssnext#299]
I am using `postcss-import` which is included as a dependency and have been getting the following message:

```
Your current PostCSS version is 5.1.0, but postcss-import uses 4.1.16. Perhaps this is the source of the error below.
```

Since I'm using Webpack and `postcss-loader`, this already adds a newer version of PostCSS as a dependency. Adding a newer version of `postcss-import` indeed resolved some unexpected errors.

Is there any reason I shouldn't be installing the plugins I'm using myself?

**Comment by MoOx** [comment]
You are talking about webpack, postcss-import and postcss-loader. Is there any issue with postcss-cssnext (which does not provide postcss-import)? If you are using "cssnext" package, this package is deprecated http://cssnext.io/postcss/.

**Comment by langri-sha** [comment]
Thanks for clearing it up @MoOx. I've looked at my container and indeed it seems that at some point I've installed `cssnext` which pulled in an olden version of `postcss-import`.
