### ISSUE TITLE
Plugin for converting new color syntax to legacy

### ISSUE THREAD

**Issue by Semigradsky** [MoOx/postcss-cssnext#300]
https://github.com/w3c/csswg-drafts/commit/a54f8b2089d16eca696690fe7ffc3c11d4db9861

**Comment by Semigradsky** [comment]
Changes in another functions: https://wiki.csswg.org/ideas/functional-notation

**Comment by MoOx** [comment]
What the fuck. This is fucking horrible.

**Comment by stevenvachon** [comment]
Doesn't look that bad to me. `rgba(0 0 0)` is like `color(black alpha(25%))`

**Comment by MoOx** [comment]
Anyway if that's the specs... Contribution welcome!

**Comment by dmarchena** [comment]
I've already working on it. You can check it here: [https://github.com/dmarchena/postcss-color-rgb](https://github.com/dmarchena/postcss-color-rgb)

**Comment by MoOx** [comment]
Ok. Is this plugin ready to be used? We can probably add it, it's pretty simple to add a feature: https://github.com/MoOx/postcss-cssnext/blob/master/CONTRIBUTING.md#add-a-feature

**Comment by dmarchena** [comment]
It's almost ready. I want to test it better this weekend and work in hsl(). I'll keep you up-to-date. Thanks for the link!

**Comment by dmarchena** [comment]
Finally I've released two plugins:
https://github.com/dmarchena/postcss-color-hsl
https://github.com/dmarchena/postcss-color-rgb

I hope to send you a pull request 	tomorrow or the day after.

**Comment by MoOx** [comment]
I closed this issue but maybe there is more transformations to add?

**Comment by dmarchena** [comment]
Maybe, but only rgb and hsl are functions from CSS Color Module Level 3. 

gray(), lab(), lch() and hwb() have functional notation too, though they are new. I think their postcss plugins should take into account the new notation, don't you?

**Comment by MoOx** [comment]
Yeah probably.

**Comment by dmarchena** [comment]
Working on rgb() and hsl() I'd thought to extract the conversion to a general purpose plugin, but it's a quite simple regexp. The real work cames from their params conversion to legacy.

Can be useful a new npm package based on a regexp to extract raw params?

Now supported:
rgb() = rgba() = rgb( <percentage>{3} [ / <alpha-value> ]? ) | rgb( <number>{3} [ / <alpha-value> ]? )
hsl() = hsla() = hsl( <hue> <percentage> <percentage> [ / <alpha-value> ]? )

Pending:
gray() = gray( <number>  [ / <alpha-value> ]? )
hwb( <hue> <percentage> <percentage> [ / <alpha-value> ]? )
lab() = lab( <number> <number> <number> [ / <alpha-value> ]? )
lch() = lch( <number> <number> <hue> [ / <alpha-value> ]? )

**Comment by ben-eb** [comment]
@dmarchena Perhaps it would be useful to add support in color-string? That way you would get the conversion functions already. 😄 

https://github.com/Qix-/color-string/issues/27

**Comment by dmarchena** [comment]
@ben-eb Interesting idea, perhaps we can give it a try. ;) 
I'll have a look into color-string code.

**Comment by desjardinsm** [comment]
> Finally I've released two plugins:
https://github.com/dmarchena/postcss-color-hsl
https://github.com/dmarchena/postcss-color-rgb
\
I hope to send you a pull request tomorrow or the day after.

It was mentioned earlier in this thread that the newer color functions like `hwb()` wouldn't need a separate plugin to handle their transformation, and rather their postcss plugin should handle it themselves. However postcss-color-hwb, for one, relies on [Qix-/color-string](https://github.com/postcss/postcss-color-hwb) to perform its parsing, but whose regexes don't handle the functional notations. What's more, the [spec for `hwb()`](https://drafts.csswg.org/css-color/#the-hwb-notation) doesn't seem to even specify that it has a comma-separated variant, being among the new color functions.

I'm not quite sure what the overall plan for this is, but I'm hoping I can help in some way.

**Comment by MoOx** [comment]
`postcss-cssnext` has been deprecated in favor or `postcss-preset-env`. Read more at https://moox.io/blog/deprecating-cssnext/
