### ISSUE TITLE
Tests not executed on Windows

### ISSUE THREAD

**Issue by Semigradsky** [MoOx/postcss-cssnext#303]
I removed all content in file `src\fatures.js`.
`npm test` after it:

> > postcss-cssnext@2.7.0 prebabelify D:\Dev\git\post-css\postcss-cssnext
> > rimraf lib

> > postcss-cssnext@2.7.0 babelify D:\Dev\git\post-css\postcss-cssnext
> > babel src --out-dir lib

> src\features-activation-map.js -> lib\features-activation-map.js
> src\features.js -> lib\features.js
> src\index.js -> lib\index.js
> src\warn-for-duplicates.js -> lib\warn-for-duplicates.js
> src\__tests__\index.js -> lib\__tests__\index.js
> src\__tests__\option.browsers.js -> lib\__tests__\option.browsers.js
> src\__tests__\option.features.js -> lib\__tests__\option.features.js
> src\__tests__\option.warnForDuplicates.js -> lib\__tests__\option.warnForDuplica
> tes.js
> src\__tests__\utils\index.js -> lib\__tests__\utils\index.js

> > postcss-cssnext@2.7.0 tape D:\Dev\git\post-css\postcss-cssnext
> > tape 'lib/__tests__/*.js'

No any errors.

---
system: Windows 8
node: v6.3.0
npm: 3.9.6

**Comment by Semigradsky** [comment]
The same when I changed some functions to noop:
```js
/* eslint-disable max-len */
export default {
  /**
   * REMINDER:
   * ******************
   * order is important
   * ******************
   */
   // https://npmjs.com/package/postcss-custom-properties
  customProperties: () => {},

  // https://npmjs.com/package/postcss-apply
  applyRule: () => {},

  // https://npmjs.com/package/postcss-calc
  calc: () => {},

...
```

**Comment by MoOx** [comment]
That's a big issue indeed. Probably related to a glob issue with the tape thing. Maybe try to replace to `tape \"lib/__tests__/*.js\"`.

**Comment by Semigradsky** [comment]
Yeah, it helped.
