### ISSUE TITLE
No @import support?

### ISSUE THREAD

**Issue by davidrossjones** [MoOx/postcss-cssnext#304]
Is there no default `@import` processing with Cssnext? I am having issues with `postcss-custom-properties` not converting new CSS vars to values when spread across partials and included into a main stylesheet using `@import`. Here's an example:

**partial1.css**
~~~
:root{
    --color-primary: blue;
}
~~~

**partial2.css**
~~~
body {
    background-color: var(--color-primary);
}
~~~

**main.css**
~~~
@import 'partial1.css';

:root{
    --color-primary: green;
}

@import 'partial2.css';

body {
    background-color: var(--color-primary);
}
~~~

**Actual CSS Output**
~~~
:root{
    --color-primary: blue;
}
body {
    background-color: var(--color-primary);
}
body {
    background-color: green;
}
~~~

**Expected CSS Output**
~~~
body {
    background-color: green;
}
~~~

Looking at the `package.json` for `cssnext` there is a dev dependency on `postcss-import` but this is not applied with the default `cssnext` rules at processing. Contrast this with another popular package `precss` which also uses `postcss-custom-properties` but also includes `postcss-import-partial` in it's processing rules whereby the expected CSS output above is the result.

Am I missing something? Should I manually include something like `postcss-import` myself? Why would this not be part of `cssnext` by default?

**Comment by MoOx** [comment]
postcss-import was included in `cssnext` package (which is deprecated in favor of `postcss-cssnext`). See http://cssnext.io/postcss/ for an explanation.
So yeah, just add postcss-import. No big deal. Lot's of people use cssnext without `@import` these days (eg: when using webpack).
