### ISSUE TITLE
Pixel fallback doesn't work in media queries

### ISSUE THREAD

**Issue by PierrickGT** [MoOx/postcss-cssnext#308]
Hi,

I've written the following function to convert pixel values to em or rem values:
```
var postCssFunctions = functions({
  functions: {
    em: function(pixels) {
      var browserContext = 16;
      var pixels = parseInt(pixels, 10);
      return pixels/browserContext;
    }
  }
});
```

That I use this way in my CSS code:
```
@media (width <= $small-window) {
  .l-help {
    box-sizing: content-box;
    padding: em(36)rem em(10)rem em(12)rem;
  }
}
```

The problem is, CSSNext correctly writes the pixel fallback when outside of a media query but not inside:

<img width="321" alt="capture d ecran 2016-08-30 a 11 15 06" src="https://cloud.githubusercontent.com/assets/2401738/18083502/a8d613e6-6ea3-11e6-9b92-7fc0a1902cdd.png">

My Gulp task is the following:
```
gulp.task('css', function() {
  var processors = [precss, postCssFunctions, cssnext, assets({
    basePath: 'public/',
    loadPaths: ['assets/images/**']
  }), browserReporter, reporter, cssnano({autoprefixer: false, zindex: false})];
  return gulp.src('./source/css/style.css')
  .pipe($.sourcemaps.init())
  .pipe($.postcss(processors))
  .pipe($.sourcemaps.write('.'))
  .pipe(gulp.dest('./public/assets/stylesheets'))
  .pipe(browserSync.stream());
});
```

Any idea why it isn't working?

**Comment by MoOx** [comment]
cssnext use pixrem for fallbacks. Fallback make only sense on IE8 (which does not understand media queries) and font prop on IE9/10. See https://github.com/robwierzbowski/node-pixrem#usage
That's why you don't have the fallback: it's useless here.
