### ISSUE TITLE
failed to require("postcss-selector-matches")

### ISSUE THREAD

**Issue by masaha03** [MoOx/postcss-cssnext#314]
postcss-selector-matches uses "export default".
When import it by commonjs require, Babel transforms it to an object like "{ default: ... }".

So, in features.js:
`require("postcss-selector-matches")(options)`
needs to be fixed to
`require("postcss-selector-matches").default(options)`

**Comment by MoOx** [comment]
Please just reinstall cssnext, postcss-selector-matches should fix that in 2.0.3
