### ISSUE TITLE
Custom selectors and nesting gone weird.

### ISSUE THREAD

**Issue by metaloha** [MoOx/postcss-cssnext#315]
CSS written:
```css
.sidebar {
    & :--heading,
    & a,
    & a:visited {}
}
```

Expected output:
```css
.sidebar h1,
.sidebar h2,
.sidebar h3,
.sidebar h4,
.sidebar h5,
.sidebar h6,
.sidebar a,
.sidebar a:visited {}
```

Actual output:
```css
h1.sidebar ,
h2.sidebar ,
h3.sidebar ,
h4.sidebar ,
h5.sidebar ,
h6.sidebar ,
a.sidebar,
d.sidebar a:visite  {}
```

This seems to have just started over the weekend (worked on Friday, fails today). What happened and where is the error coming from?

**Comment by MoOx** [comment]
Ouch this seems related to postcss-selector-matches 2.0.2 release. @yordis can you take a look? This is a big issue.

**Comment by MoOx** [comment]
Meanwhile @metaloha try adding this in your deps: `"postcss-selector-matches": "2.0.1"`, then `npm uninstall  postcss-cssnext` and `npm install` to get postcss-cssnext back with the bugfree version of postcss-selector-matches`.

**Comment by MoOx** [comment]
What is the content of :--heading btw?
I think I have a fix. Try to uninstall & reinstall cssnext, it should be fine.

**Comment by metaloha** [comment]
Fantastic, doing that worked :) Thanks for the FAST turnaround on it!.

The `heading` custom selector was pretty much what you'd expect it to be: `@custom-selector :--heading h1, h2, h3, h4, h5, h6;`

**Comment by MoOx** [comment]
So the bug have been correctly fixed upstream. Should be good now!

**Comment by yordis** [comment]
@MoOx is it fix?
