### ISSUE TITLE
Transform shorthand 

### ISSUE THREAD

**Issue by kevinSuttle** [MoOx/postcss-cssnext#320]
It appears to be spec-compliant.

@MoOx @jonathantneal would it make sense to include it here? 
https://github.com/jonathantneal/postcss-transform-shortcut

**Comment by MoOx** [comment]
This has already been discussed in #290. Next time please use the search :)

**Comment by kevinSuttle** [comment]
I swear I did and these didn't come up. :/

**Comment by MoOx** [comment]
https://github.com/MoOx/postcss-cssnext/issues?utf8=%E2%9C%93&q=is%3Aissue%20transform

**Comment by kevinSuttle** [comment]
Yeah, I know how search works.
