### ISSUE TITLE
Include instruction to disable autoprefixer for cssnano

### ISSUE THREAD

**Issue by Purii** [MoOx/postcss-cssnext#323]
The [documentation](http://cssnext.io/postcss/) suggests using `cssnano` for compression:

``` javascript
...
.pipe(postcss([
      require("postcss-import")(),
      require("postcss-url")(),
      require("postcss-cssnext")(),
      // add your "plugins" here
      // ...
      // and if you want to compress
      // require("cssnano")(),
      require("postcss-browser-reporter")(),
      require("postcss-reporter")(),
    ]))
...
```

Simply uncommenting `cssnano` will trigger the known warning `[...]postcss-cssnext found a duplicate plugin ('autoprefixer') in your postcss plugins.[...]`.

Wouldn't it make sense to update that line?

``` javascript
require('cssnano')({ autoprefixer: false }),
```

**Comment by MoOx** [comment]
Good idea!

**Comment by piotr-cz** [comment]
Why autoprefixer should be disabled in _cssnano_ and not in _postcss-cssnext_ features?

**Comment by MoOx** [comment]
Because cssnano main goal is to reduce your CSS. cssnext main goal is to automatically allows you to write standard CSS without thinking about it.

**Comment by piotr-cz** [comment]
That makes sense.
Just that the cssnano autoprefixer [docs say](http://cssnano.co/optimisations/autoprefixer/) that by default it's used to strip vendor prefixes. So it seems to me the same plugin is used for two different things
