### ISSUE TITLE
postcss-cssnext webpack 2 config example

### ISSUE THREAD

**Issue by janusch** [MoOx/postcss-cssnext#325]
Sorry, if this is the wrong repo in your opinion to address this issue, I am just not sure where to turn to anymore. And I saw that you probably have it working somewhere: https://github.com/webpack/webpack/issues/2684 

I am using react-toolbox@2 with webpack@2 and cannot get it to transpile variables and probably other cssnext features into css. 
Do you have a working webpack 2 config or an example repo that you can share?

The use case is that I need the postcss-cssnext cssmodules webpack 2 toolchain for react-toolbox, and besides that the css that is not from expternal modules is written in scss + cssmodules.

Some help would be greatly appreciated!

**Comment by MoOx** [comment]
You should find something here https://github.com/MoOx/phenomic/blob/290976455fe11a5d4afd666f832e1ddf1dee3a56/themes/phenomic-theme-base/webpack.config.js
