### ISSUE TITLE
Dedupe dependencies.

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [MoOx/postcss-cssnext#327]
Several of the packages on which `postcss-cssnext` depends share dependencies (`postcss`, `balanced-match`, et cetera).  However, since some of them are pinned to difference versions than others, multiple versions of these sub dependencies are downloaded.  For `postcss-cssnext@2.8.0`, it looks like four versions of `color`, three versions of `balanced-match`, and two versions of each `supports-color`, `postcss-selector-parser`, `color-string`, `color-name`, and `color-convert` are required.  I am not sure if it is an actionable issue, but could something be done so that these can be deduped?

**Comment by MoOx** [comment]
I guess one thing to do is to contribute to each dependencies.

**Comment by wtgtybhertgeghgtwtg** [comment]
I compiled a list of packages to be updated to dedupe the dependencies.
- [ ] Bump `color` in [`postcss-color-rebeccapurple`](https://github.com/postcss/postcss-color-rebeccapurple).
- [ ] Bump `color` in [`postcss-color-gray`](https://github.com/postcss/postcss-color-gray).  This is already done, but they have yet to publish the patch to NPM.
- [ ] Bump `color` in [`postcss-color-hwb`](https://github.com/postcss/postcss-color-hwb).
- [ ] Bump `balanced-match` in [`postcss-selector-not`](https://github.com/postcss/postcss-selector-not).
- [ ] Bump `balanced-match` in [`postcss-custom-properties`](https://github.com/postcss/postcss-custom-properties).
- [ ] Bump `supports-color` in [`chalk`](https://github.com/chalk/chalk).  This is already done, but they have yet to publish the patch to NPM.
- [ ] Bump `postcss-selector-parser` in [`postcss-pseudo-class-any-link`](https://github.com/jonathantneal/postcss-pseudo-class-any-link).

I will see if they accept PR's for these.

**Comment by MoOx** [comment]
I am the author of most packages so there won't be any problem for most ;)

**Comment by MoOx** [comment]
I merged the PR you made including this one https://github.com/MoOx/reduce-function-call/pull/5.
I checked some boxes in your previous comment :)

chalk updates for supports-color has landed a while ago. it seems to be in 1.1.2.

**Comment by wtgtybhertgeghgtwtg** [comment]
I don't know how I missed that `chalk` thing.
PR's filed for `postcss-selector-not` and `postcss-custom-properties`.

**Comment by wtgtybhertgeghgtwtg** [comment]
The latest version of`postcss-pseudo-class-any-link` uses the latest version of `postcss-selector-parser`, but [the minimum supported `node` version](https://github.com/jonathantneal/postcss-pseudo-class-any-link/blob/master/package.json#L21) is too high to use.
Not strictly part of this issue, but https://github.com/Nyalab/caniuse-api/pull/54 would also help reduce dependencies.

**Comment by MoOx** [comment]
@wtgtybhertgeghgtwtg any update on the work done here?

**Comment by wtgtybhertgeghgtwtg** [comment]
More duplicates have sprung up.  I will compile a list shortly.

**Comment by MoOx** [comment]
Ouch. Anything to share on how to catch these?

**Comment by wtgtybhertgeghgtwtg** [comment]
There's a visualization tool: http://npm.anvaka.com/#/view/2d/postcss-cssnext
The duplicates are `supports-color`, `balanced-match`, `ansi-styles`, `has-flag`, `chalk`, `postcss`, `browserslist`, `color`, `color-string`, and `reduce-css-calc`.
I think the best way to get some of this out of the way would be to get the packages that still use `postcss@5` up to `postcss@6`.  That would be `postcss-color-rgba-fallback`, `postcss-pseudoelements`, and `pixrem`.

**Comment by MoOx** [comment]
#401 might help... My bad on this...

**Comment by MoOx** [comment]
`postcss-cssnext` has been deprecated in favor or `postcss-preset-env`. Read more at https://moox.io/blog/deprecating-cssnext/
