### ISSUE TITLE
v3.0 discussion

### ISSUE THREAD

**Issue by MoOx** [MoOx/postcss-cssnext#329]
I am thinking about:

- add stage/level option #100 by default (and maybe disable some plugins?)

Any other ideas?

--- 

To merge and release for v3

- #337
- #333 
- #318  (`@apply` update and breaking change)
- bump postcss-color-function to latest (small major change)

**Comment by jonathantneal** [comment]
Looks great. What will you need to move forward? I might also add:

- merge #333

**Comment by simonkberg** [comment]
Regarding #333, which would require dropping support for every node version below 6:

I don't personally use Node v4 for any active projects currently, but I would just like to clarify that there are _two_ active LTS branches, and v4 won't enter maintenance mode until April this year, which it will stay in for 12 months until finally reaching its EOL in April 2018.

So: dropping support for Node v4 doesn't affect me personally, but it does however affect the stability of the ecosystem, which is something to take into consideration. It still also has [wide usage][1].

From a quick look at `postcss-pseudo-class-any-link` it seems like the [destructuring and 
default function parameter][2] is the only thing preventing v4 compatibility.

[1]: https://twitter.com/seldo/status/817030501341032448
[2]: https://github.com/jonathantneal/postcss-pseudo-class-any-link/blob/master/index.js#L6-L8

**Comment by MoOx** [comment]
Indeed, just this small syntax sugar should be replaced for a better compat imo!

**Comment by MoOx** [comment]
FYI https://twitter.com/MoOx/status/826674905215336450

**Comment by MoOx** [comment]
@jonathantneal for #100 this is not just a new feature, but will be a breaking change as we will probably disable some by default ( or maybe at least in another major version...)

**Comment by jonathantneal** [comment]
Happy to add compat if someone can show me a pattern for producing a v4 and v6 version.

Unrelated question. Will v6 leverage browserslist?

**Comment by MoOx** [comment]
browserlist is already used (maybe not the latest version...)

**Comment by MoOx** [comment]
Time to remove apply? http://www.xanthir.com/b4o00

**Comment by Semigradsky** [comment]
Is there any likelihood that [nesting specification](https://tabatkins.github.io/specs/css-nesting/) will become official? Or we should remove it too?

**Comment by pascalduez** [comment]
> Time to remove apply? http://www.xanthir.com/b4o00

I would say so... 
Users heavily relying on it can always add the [plugin](https://github.com/pascalduez/postcss-apply) in standalone mode.

More links:  
https://discourse.wicg.io/t/needed-new-champion-for-css-apply-rule/2012  
https://github.com/w3c/webcomponents/issues/300#issuecomment-276210974

**Comment by dbox** [comment]
> Time to remove apply? http://www.xanthir.com/b4o00
> Is there any likelihood that nesting specification will become official? Or we should remove it too?

Let me start this by saying I love cssnext and give a huge thanks to everyone involved.

I know it's been discussed before but the major issue here  is that CSSWG has no real "stages" of completion. @jonathantneal has tried to spearhead a new system for  this: https://github.com/jonathantneal/css-db. But until CSSWG and cssnext can be more aligned, then the concept of cssnext doesn't work.

The concept, at least how it's presented, and how I initially understood, it was to write "future-proof*" css. But that can't be done if we're allowing uncertain specs in.

IMHO the only way cssnext is relevant is to be *very* sure the spec'd features are actually coming, and CSSWG makes this almost impossible until the features are essentially available all browsers.

I want nothing more than to use nesting and apply (or whatever mixin solution comes next), but the archaic and crawling pace of csswg has our hands tied. Apply and nesting were, imho the last 2 things needed to really ditch standard preprocessors and move to a fully standards-compliant workflow.

I don't have any solutions really, other than wondering if there is some way we can as a group pressure CSSWG for more transparency/teamwork or to get them on a better system like @jonathantneal has suggested. 

 Does anyone have contacts within CSSWG that could get the latest status update on nesting? (Clearly apply has to be removed now - it's dead.  😞 )

**Comment by pepelsbey** [comment]
If I may, I’d really recommend cssnext to focus on future-proof promise it once gave us. To become a Babel to CSS. It requires setting a strict bar to determine what to support: Tab’s napkin-drafts or something ready to be implemented or _already_ implemented by browsers (I’d prefer the second). You could always abstract out all nesting fantasies to PostCSS plugins for everyone eager to use it, while keeping project truly cssnext, not cssfantasies.

**Comment by jonathantneal** [comment]
@pepelsbey, `@apply` was a unique situation. For a time it seemed like one of the ”safer“ features within cssnext, as Chrome had already implemented it behind a flag. We only later learned the csswg had never given it a formal blessing after Tab lost interest and a few of us requested it be given a new champion.

I’d love an opportunity to “sit down” with csswg members and walk through the drafts we‘ve implemented to see where they rest on some scale of realism. With such information, we really could do something like babel, including the introduction of stages.

**Comment by MoOx** [comment]
Some issues will be/have been handled in #400. Some other are still open.
