### ISSUE TITLE
looking for guidance on postcss-apply features API

### ISSUE THREAD

**Issue by JustAboutJeff** [MoOx/postcss-cssnext#335]
thanks for creating `postcss-cssnext` ! All of the underlying postcss plugin options are exposed with the [handy features API ](http://cssnext.io/usage/#features) like so:

```
const { variables, extensions } = require('./variables')

module.exports = function postcss () {
  return {
    plugins: {
      'postcss-import': {},
      'postcss-url': { url: 'inline' },
      'postcss-cssnext': {
        browsers: ['last 2 versions'],
        features: {
          customProperties: { variables },
          customMedia: { extensions }
        }
      }
    }
  }
}
```

I was attempting to inject a few custom property `@apply` rules in a similar manner but didn't see an obvious way to do so in the docs or source. Can someone enlighten me how that would be done? cc @pascalduez perhaps ?

**Comment by pascalduez** [comment]
Hi @JustAboutJeff,

it's simply not implemented currently, so obviously not possible.
The `postcss-apply` plugin is trying to stay "minimalistic" somehow.

Nonetheless, this seem to confuse quite a few users, so I guess I'll add it.
See pascalduez/postcss-apply/issues/15

**Comment by JustAboutJeff** [comment]
@pascalduez thanks for the helpful response!
