### ISSUE TITLE
Missed semicolon in nested rules

### ISSUE THREAD

**Issue by kostyandrew** [MoOx/postcss-cssnext#338]
I got missed semicolon for last rule near or inside nested group:
```
@use postcss-cssnext;
.class {
  font-size: 1em;
  color: black;
  & .a {
    font-size: 1em;
    color: red;
  }
}

.b {
  font-size: 1em;
  color: black;
}
```

```
.class {
  font-size: 1em;
  color: black
}

.class .a {
  font-size: 1em;
  color: red
}

.b {
  font-size: 1em;
  color: black;
}
```

How you see, color rules with nesting don't have semicolon

**Comment by MoOx** [comment]
I guess that's an issue related to postcss-nesting. See https://github.com/jonathantneal/postcss-nesting/issues/20

Code is still valid so I won't consider it's a bug :)
