### ISSUE TITLE
BUG: SVG Hex code getting converted to RGBA

### ISSUE THREAD

**Issue by luangjokaj** [MoOx/postcss-cssnext#339]
There is a bug when I try to import webfonts in SVG format with a very long HEX code at the end of the font url. The hex code is being converted automatically to RGBA. This is caused by cssnext, when I disable cssnext everything works correctly.

**This is how I import the SVG format of the font:**
`url("Fonts/e4d5b881-6835-45b7-8766-3e5b9e7cab8b.svg#e4d5b881-6835-45b7-8766-4e5b9e7cab7c") format("svg");`

**And this is the output:**
`url("Fonts/e4d5b881-6835-45b7-8766-3e5b9e7cab8b.svgrgba(228,213,184,.50588)-6835-45b7-8766-4e5b9e7cab7c") format("svg");`

Is this a known issue? Or is there any work around?

**Comment by MoOx** [comment]
I guess it's a bug from https://github.com/postcss/postcss-color-hex-alpha

**Comment by bbodien** [comment]
I've worked around this by disabling postcss-color-hex-alpha in my postcss.config.js:

```
module.exports = {
  plugins: {
    ...
    'postcss-cssnext': {
      features: {
        colorHexAlpha: false
      }
    },
    ...
  }
}

```

**Comment by MoOx** [comment]
`postcss-cssnext` has been deprecated in favor or `postcss-preset-env`. Read more at https://moox.io/blog/deprecating-cssnext/
