### ISSUE TITLE
browserlist  "not ie <= x" support not functional

### ISSUE THREAD

**Issue by Learn-Digital-Audio** [MoOx/postcss-cssnext#343]
Hello,

I am using:

  "devDependencies": {
    "gulp": "^3.9.1",
    "gulp-postcss": "^6.3.0",
    "postcss-cssnext": "^2.9.0"

and when I add:

  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 10"
  ]

To my package.json file it NEARLY works! I can manipulate the "> %" and "last x versions" and it works fine, BUT the final "not ie <= x" does nothing and does not work.

This "not" feature was added to browserlist  2015 I think? Any idea of the problem? Thanks!

**Comment by MoOx** [comment]
Probably a dup of #341

**Comment by Learn-Digital-Audio** [comment]
Hi MoOx,

I am a bit confused. Your main site http://cssnext.io/usage/ says:

> # browsers

> (default: **browserslist** default > 1%, last 2 versions, Firefox ESR, Opera 12.1)

> Allows you to specify your browser scope. This option enables or disables features according to caniuse database. This is the exact same option that you might know from Autoprefixer. Since cssnext includes Autoprefixer, the option is propagated.

> **See Browserslist queries syntax to adjust this option to your needs.**

But you are closing this issue as a duplication of **Add browserlist support #341**?

It clearly says that postcss-cssnex already uses browserslist  and that you can "adjust this option to your needs"? Sorry If i am missing something obvious here, THANKS for the fantastic free software!

**Comment by MoOx** [comment]
Previous version of browserslist were not handling the browserlist config automatically from files. It's that simple. We need to update packages here and in deps.
