### ISSUE TITLE
`npm test` failed on Windows

### ISSUE THREAD

**Issue by Semigradsky** [MoOx/postcss-cssnext#344]
> npm: 3.10.6
> nodejs: 6.3.1

Failed tests:
- > not ok 2 should pass the regression
  > ---
  >  operator: equal
    expected: |-
      '.button {\r\n}\r\n\r\n.button i {\r\n\r\n    color: black\r\n}'
    actual: |-
      '.button {\r\n}\r\n\r\n.button i {\r\n\r\n    color: black\n}'
    at: Test.<anonymous> (E:\Dmitry\git\postcss\postcss-cssnext\lib\__tests__\index.js:30:5)
  ...

- > not ok 23 should add nesting support
  > ---
  >  operator: equal
    expected: |-
      '.foo {\r\n  color: red\r\n}\r\n.foo .bar {\r\n  color: white\r\n}'
    actual: |-
      '.foo {\r\n  color: red\r\n}\n.foo .bar {\r\n  color: white\r\n}'
    at: testFeature (E:\Dmitry\git\postcss\postcss-cssnext\lib\__tests__\option.features.js:41:5)
  ...

- > not ok 32 should add customSelectors support
  > ---
  >  operator: equal
    expected: |-
      'article h1 + p,\r\narticle h2 + p,\r\narticle h3 + p,\r\narticle h4 + p,\r\narticle h5 + p,\r\narticle h6 + p{\r\n  margin-top: 0;\r\n}'
    actual: |-
      'article h1 + p,\narticle h2 + p,\narticle h3 + p,\narticle h4 + p,\narticle h5 + p,\narticle h6 + p{\r\n  margin-top: 0;\r\n}'
    at: testFeature (E:\Dmitry\git\postcss\postcss-cssnext\lib\__tests__\option.features.js:41:5)
  ...

**Comment by MoOx** [comment]
Not sure what changed since it's ok on the CI

**Comment by MoOx** [comment]
It seems a module is placing some hardcoded \n instead of \r\n. Please reopen if still relevant as it's ok on CI.
