### ISSUE TITLE
Pseudo unit problem

### ISSUE THREAD

**Issue by dYb** [MoOx/postcss-cssnext#349]
```
// before processing
body {
  width: 1rem;
}
body: after {
  width: 2rem;
}
// after transformation
body {
  width: 1rem;
}
body: after{
  width: 16px;
  width: 1rem;
}
```

I set `browserlist` to `['> 1%', 'last 2 versions', 'Firefox ESR', 'Opera 12.1', 'ie > 8', 'Android >= 4.0', 'iOS > 7']`.
It should not contain px unit, but for pseudo element, it did.

**Comment by MoOx** [comment]
Probably related to https://github.com/MoOx/postcss-cssnext/issues/341

**Comment by dYb** [comment]
Maybe. but there are some difference.
Only in pseudo element was transformed to px unit.
Temporarily, I use `{ features: { rem: false }}` to disable the feature
