### ISSUE TITLE
How do you configure this?

### ISSUE THREAD

**Issue by bradennapier** [MoOx/postcss-cssnext#350]
Documentation is lacking in quite a few places.  I'd be happy to help / add to them in places I know about but this one I simply can not figure out!

Anyway, in my postcss.config.js I tried to follow and translate whatever it is described and it does not work.  I have about 1,000 warnings on startup printed to the logs which I do not want to see - they are all about the :root in customproperties which says I should be able to set warnings to false...nothing happens.

I read another post which apparently claims in order to give this plugin settings I need some other plugin to make this plugin work?  I don't get it... can we make this plugin work with settings so that we can configure things?

This does not work:

```js
module.exports = {
  plugins: [
    require('postcss-import')({}),
    require('postcss-cssnext')({
      browsers: [ 'last 2 versions', '> 5%'],
      features: {
        customProperties: {
          warnings: false
        }
      }
    }),
    require('precss')({ /* ...options */ }),
  ]
}
```

**Comment by bradennapier** [comment]
Yeah upon reading it 2-3 more times I still don't see how the others fixed it.

**Comment by Semigradsky** [comment]
`warnings: false` doesn't disable ALL warnings.
See https://github.com/postcss/postcss-custom-properties#warnings

> For now, it only allow to disable messages about custom properties definition not scoped in a :root selector.

**Comment by MoOx** [comment]
Warnings are here for a reason. Just fix the reason.

**Comment by dutscher** [comment]
```
require('postcss-cssnext')({
            features: {
                customProperties: {
                    globalWarnings: false,
                    warnings: false,
                },
            },
        }),
```
works for me ;)
