### ISSUE TITLE
Modifying a variable in custom property does not work

### ISSUE THREAD

**Issue by helguita** [MoOx/postcss-cssnext#351]
Hello,

I setup some variables in my config file like this:

```
'postcss-cssnext': {
      features: {
        customProperties: {
          variables: {
            mainColor: "red",
          }
        }
      }
    }
```

However when I change the value from `mainColor` from red to green it doesn't change in the website.

Any pointers on why this is happening?

Thanks a bunch!

**Comment by Semigradsky** [comment]
Variables in config override any that exist in the CSS.
See https://github.com/postcss/postcss-custom-properties#variables
