### ISSUE TITLE
Disable px fallback for rem/em

### ISSUE THREAD

**Issue by lukasoppermann** [MoOx/postcss-cssnext#354]
Hey, so I have cssnext set to latest 2 versions

```
require('postcss-cssnext')({
  browsers: ['last 2 versions']
}),
```

However, I still get the fallback for rem/em to px. Is this because of opera mini? I would like to disable it, since I don't need it. How is this possible?

**Comment by deltragon** [comment]
you can disable individual features: http://cssnext.io/usage/
```
require('postcss-cssnext')({
  browsers: ['last 2 versions'],
  features: {
    rem: false
  }
}),
```

**Comment by lukasoppermann** [comment]
I tried this before and tried it now again, somehow it is not working for me. 😢 Any Idea what I could be doing wrong?

```
.pipe(postcss([
          require('postcss-import')(),
          require('postcss-will-change'),
          require('postcss-discard-comments'),
          require('postcss-cssnext')({
            browsers: ['last 2 versions'],
            features: {
              rem: false
            }
          }),
          require('cssnano')({
            autoprefixer: false,
            discardComments: {
              removeAll: true
            }
            // zindex: false
          }),
          require('postcss-reporter')({
            plugins: [
              'postcss-color-function'
            ]
          })
        ]))
```

**Comment by deltragon** [comment]
are you sure it's cssnext and not some other plugin? the rem fallback is not even used in the standard browserlist configuration anymore.
Have you tried a clean setup, without other postcss plugins?

**Comment by lukasoppermann** [comment]
Good idea, but yes, I have 2.10.0 installed and if I remove all plugins but the `cssnext` it is still changed by it.

**Comment by deltragon** [comment]
Cannot reproduce.

**Comment by lukasoppermann** [comment]
Okay, I figure something out, it is actually NOT, as you guessed, the rem plugin, but it happens when using fallback values in `var()`, I guess I will open a new ticket for this.

**Comment by 11bits** [comment]
Hi, I have the same problem using cssnext with the default configuration.

`package.json`

```
    "devDependencies": {
        "postcss-cli": "^5.0.0",
        "postcss-cssnext": "^3.1.0",
        "postcss-import": "^11.1.0"
    },
    "scripts": {
        "postcss": "postcss assets/styles/src/style.css -u postcss-import postcss-cssnext -d assets/styles/ --no-map -w"
    }
```

`base.css`

```
html {
    font-size: 1rem;
}
```

output:

```
html {
    font-size: 16px;
    font-size: 1rem;
}
```

Is it possible to disable rem fallback from package.json or I need another config file?
