### ISSUE TITLE
Attribute selector not working 

### ISSUE THREAD

**Issue by ashokkumarsand** [MoOx/postcss-cssnext#355]
I am unable to process following css syntax
`.className[attribute='value'] {

}`

or 
`.className:hover+label {

}`

**Comment by MoOx** [comment]
define "unable to process"
It's perfectly parsed and stringified in the playground.

**Comment by ashokkumarsand** [comment]
@MoOx I am using this with react-css-module and this is not applied when i use with reactJS as node module. and this give me no error but not applied to my elements. 
are you having and other example or proper syntax for different selector for css-next. That is also not available on your document

**Comment by MoOx** [comment]
Sorry but it looks like cssnext is not the problem here as the output is the same as the input.
