### ISSUE TITLE
Update postcss-apply to the latest version

### ISSUE THREAD

**Issue by kagawagao** [MoOx/postcss-cssnext#361]
please update `postcss-apply` to the latest version, there is an important feature: support `sets` option, but in the current version in `postcss-cssnext` do not support `options`

**Comment by Semigradsky** [comment]
#318

**Comment by MoOx** [comment]
Hum... http://www.xanthir.com/b4o00

**Comment by MoOx** [comment]
Done in #400, but will be removed in next major.
