### ISSUE TITLE
Not outputing the font face which is not used anywhere

### ISSUE THREAD

**Issue by ashokkumrjt** [MoOx/postcss-cssnext#362]
Declared a font face like below

@font-face{
font-family:<NAME>;
src:url(<font-path>.otf)
}

Since I didn't use this font family, system ignores this declaration, not outputing this content in the target

**Comment by Semigradsky** [comment]
http://cssnext.io/playground/
![image](https://cloud.githubusercontent.com/assets/1198848/24420898/18a6ee58-13fd-11e7-9dca-eb84f76e9a19.png)

**Comment by MoOx** [comment]
Indeed that's not a cssnext problem.
