### ISSUE TITLE
"flow-root" support

### ISSUE THREAD

**Issue by revyh** [MoOx/postcss-cssnext#364]
How about to support [flow-root](https://github.com/fliptheweb/postcss-flow-root)?

**Comment by MoOx** [comment]
If this is safe why not. Can you provide link to specification and approve that is perfectly safe transformation?

**Comment by revyh** [comment]
[The spec](https://drafts.csswg.org/css-display/#valdef-display-flow-root) says that `flow-root` is like `display: block`, but creates new BFC. For now, there is no way to create new BFC without some side effects (like `column-count` and `overflow` fallbacks do). And `clearfix` fallback doesn't even create new BFC. So there is no perfectly safe transformation for `flow-root` ([more on this](http://codepen.io/SelenIT/pen/ggRVbG/)). And some issues in current implementation ([1](https://github.com/fliptheweb/postcss-flow-root/issues/3), [2](https://github.com/fliptheweb/postcss-flow-root/issues/4)) make this transform even more unsafe.

But if issues in this plugin will be resolved than `column-count` may be relatively safe transform (it has minimum side effects). Or may be not. I'm not really sure. Also `column-count`'s [browser support](http://caniuse.com/#feat=multicolumn) may be not enough.

**Comment by OliverJAsh** [comment]
> column-count may be relatively safe transform (it has minimum side effects)

In my experience this is not a safe fallback. See:

- https://bugs.chromium.org/p/chromium/issues/detail?id=780733
- http://jsbin.com/bexewig/4

**Comment by MoOx** [comment]
`postcss-cssnext` has been deprecated in favor or `postcss-preset-env`. Read more at https://moox.io/blog/deprecating-cssnext/
