### ISSUE TITLE
Support redefining of css variables in CSS selector instead of only in :root

### ISSUE THREAD

**Issue by ankurp** [MoOx/postcss-cssnext#365]
[postcss-css-variables](https://github.com/MadLittleMods/postcss-css-variables) allows CSS variables to be redefined inside of a CSS selector as such

```
.button {
  --button-padding: 10px;
}
```

Is this or can this be supported as currently variables can only be redefined in `:root`

**Comment by MoOx** [comment]
Please read carefully the warnings here: https://github.com/postcss/postcss-custom-properties#readme

tl;dr: impossible in a safe way.
