### ISSUE TITLE
Upgrade to postcss 6.x

### ISSUE THREAD

**Issue by Semigradsky** [MoOx/postcss-cssnext#374]
This requires a major version bump.

[PostCSS Changelog](https://github.com/postcss/postcss/blob/master/CHANGELOG.md#60-marquis-orias)

**Comment by Semigradsky** [comment]
"dependencies": {
    "autoprefixer": "^7.0.0",
    "caniuse-api": "^2.0.0",
    "chalk": "^1.1.1",
- [ ]    "pixrem": "?",
- [ ]    "pleeease-filters": "?",
    "postcss": "^6.0.0",
- [ ]    "postcss-apply": "?",
- [x]    "postcss-attribute-case-insensitive": "^2.0.0",
- [ ]    "postcss-calc": "?",
- [ ]    "postcss-color-function": "?",
- [ ]    "postcss-color-gray": "?",
- [ ]    "postcss-color-hex-alpha": "?",
- [ ]    "postcss-color-hsl": "?",
- [ ]    "postcss-color-hwb": "?",
- [ ]    "postcss-color-rebeccapurple": "?",
- [ ]    "postcss-color-rgb": "?",
- [ ]    "postcss-color-rgba-fallback": "?",
- [ ]    "postcss-custom-media": "?",
- [ ]    "postcss-custom-properties": "?",
- [ ]    "postcss-custom-selectors": ""?",
- [ ]    "postcss-font-family-system-ui": "?",
- [ ]    "postcss-font-variant": "?",
- [ ]    "postcss-initial": "?",
- [ ]    "postcss-media-minmax": "?",
- [ ]    "postcss-nesting": "?",
- [ ]    "postcss-pseudo-class-any-link": "?",
- [ ]    "postcss-pseudoelements": "?",
- [ ]    "postcss-replace-overflow-wrap": "?",
- [ ]    "postcss-selector-matches": "?",
- [ ]    "postcss-selector-not": "?"
  },

**Comment by MoOx** [comment]
Thanks for this issue. Feel free to make PR whenever you can (lot of work, I know).
I just gave you push access to this repo since you contributed a lot already.
I will do the same for all other repo I can as soon as I will see PR on (and if you ask for it).

**Comment by JLHwung** [comment]
"postcss-font-family-system-ui": "^2.0.0"

**Comment by ben-eb** [comment]
I've released https://github.com/postcss/postcss-calc/releases/tag/v6.0.0.

**Comment by svipben** [comment]
I think it's related, with latest `postcss-loader` this package (`postcss-cssnext`) isn't working.

Config part in `webpack`:

```
{
            // PostCSS loader to postprocesses CSS with PostCSS plugins.
            loader: 'postcss-loader',
            options: {
              // Makes it referenceable by other loaders.
              ident: 'postcss',
              plugins: () => [
                // Transforms CSS specs into more compatible CSS so don't need to wait for browser support.
                cssnext({
                  /**
                   * List of browsers query which are supported in project.
                   * Options passed to `cssnext`:
                   *  - `> 1%` -> versions selected by global usage statistics.
                   *  - `last 4 versions` -> the last 4 versions for each major browser.
                   *  - `Firefox ESR` -> the latest [Firefox ESR] version.
                   *  - `not ie < 9` -> exclude IE 8 and below, because React supports only IE 9 and above.
                   */
                  browsers: [
                    '> 1%',
                    'last 4 versions',
                    'Firefox ESR',
                    'not ie < 9'
                  ]
                })
              ]
            }
          }
```

P.S. Everything is fine with `postcss-loader` 1.3.3, but not the latest!

**Comment by jonathantneal** [comment]
I released https://github.com/jonathantneal/postcss-nesting which is now using v6

**Comment by jonathantneal** [comment]
@Semigradsky, I have PRs for updating postcss-rebeccapurple.

https://github.com/postcss/postcss-color-rebeccapurple/pull/9 — updates PostCSS to v6, updates other dependencies, improves the plugin to not partially update invalid colors like oldrebeccapurple.

https://github.com/postcss/postcss-color-rebeccapurple/pull/8 — just updates PostCSS to v6.

I made them separate PRs incase @MoOx had no interest in the other improvements at this time (or if he found them not to be suitable improvements).

**Comment by jonathantneal** [comment]
@Semigradsky, https://github.com/jonathantneal/postcss-pseudo-class-any-link is also updated.

**Comment by jonathantneal** [comment]
@Semigradsky, PR submitted for postcss-replace-overflow-wrap

https://github.com/MattDiMu/postcss-replace-overflow-wrap/pull/5

**Comment by MoOx** [comment]
@jonathantneal @Semigradsky I created a cssnext team in postcss org and you have been added as collab there. Will add you as collab on npm on each repo I have the rights on.

**Comment by MoOx** [comment]
My workflow is: commits + a "x.y.z" commit with changelog notes + package.json version bump + "npm run release" (see scripts ;)). You are the bosses here :)

**Comment by MoOx** [comment]
My recommendation will be to move to a monorepo for the repos we can + remove jscs and all outdated stuff in favor of eslint + eslint-config-i-am-meticulous + prettier + jest (with snapshots) but that might take some time :D

**Comment by michael-ciniawsky** [comment]
High priority ⚠️  ladies and gentlenerds 😛 how can someone help? Any blockers in one of the plugins ?

**Comment by ben-eb** [comment]
There's ways of expressing that sentiment that aren't condescending & rude, please show some respect for those of us who work on this stuff in our spare time.

**Comment by michael-ciniawsky** [comment]
@ben-eb 😟 That wasn't meant to be consdescending or rude, I also asked how to help getting the last bits done 😕

**Comment by jonathantneal** [comment]
@michael-ciniawsky, @Semigradsky, please review https://github.com/MoOx/postcss-cssnext/pull/384

**Comment by pixelass** [comment]
https://github.com/postcss/gulp-postcss/issues/118

**Comment by doochik** [comment]
Hi! Seems that last deps is merged https://github.com/MattDiMu/postcss-replace-overflow-wrap/pull/5 and new version have been released (`postcss-replace-overflow-wrap@2.0.1-0`).

Could you release new cssnext version?

**Comment by felixsanz** [comment]
What is missing here? Any plugin still needs update?

**Comment by jonathantneal** [comment]
For now, I can’t keep up. One of this can be merged and we can work from there, or it will be easier for me to release a different plugin with stages like babel.

**Comment by TeChn4K** [comment]
Any update on this issue ?

**Comment by arturparkhisenko** [comment]
Any sense update to chalk 2? And yes, any :up: ?

**Comment by MoOx** [comment]
@jonathantneal cant we ship a thing until a new solution that include stages is ready?

**Comment by MoOx** [comment]
Closing in favor of #400
