### ISSUE TITLE
Document the peer dependency to caniuse-db

### ISSUE THREAD

**Issue by googol** [MoOx/postcss-cssnext#379]
Please add documentation about this in the changelog and setup guide.

Npm won't install peer dependencies automatically, and the missing peer dependency will cause npm not to write a shrinkwrap automatically so this is an important thing to mention.

**Comment by MoOx** [comment]
If you reinstall cssnext (+ clean node_modules), you should have the correct dependency.

**Comment by googol** [comment]
Since npm v3 peer dependencies are not automatically installed https://github.com/npm/npm/releases/tag/v3.0.0

At least for me that's how it works.

**Comment by MoOx** [comment]
cssnext use caniuse-api, which have caniuse-db as a dep, so this should not be a real problem.

**Comment by MoOx** [comment]
unless you just upgrade postcss-cssnext

**Comment by MoOx** [comment]
Fresh install handle this. And a peer dep warning is already a kind of documentation :)
