### ISSUE TITLE
Webpack build fails after upgrade to postcss-cssnext 2.11.0

### ISSUE THREAD

**Issue by Vinnl** [MoOx/postcss-cssnext#381]
This is basically the same issue as #357, but [the cause](https://github.com/MoOx/postcss-cssnext/issues/357#issuecomment-287494960) this time is not `css-rrggbbaa` but `css-image-map`.

I've submitted #380 to fix this.

**Comment by YasserKaddour** [comment]
Thanks, I had the same problem upgrading `caniuse-db` fixed the issue.

**Comment by jimboslicethat** [comment]
@YasserKaddour this works great if you have a direct dependency upon `caniuse-db`. But if you are like me and do not, then adding a `peerDependency` to the package.json feels super hacky.

**Comment by Vinnl** [comment]
@YasserKaddour Be aware that if you throw away your `yarn.lock`, you're also throwing away all the benefits of using Yarn - i.e. you'll get the newest versions of all your dependencies again.

@jimboslicethat Yes, and modifying the resolved dependency is `yarn.lock` is somewhat less so, but still hacky. I hope the PR will get accepted and that the peerDependency will be kept up-to-date when new capabilities are added in the future; as far as I know that's the only non-hacky solution :)

**Comment by YasserKaddour** [comment]
@Vinnl Thanks,I knew about the risk of deleting `yarn.lock`, but I didn't mind and everything worked just fine. 
Just a question for next time, how can I quickly get the resolved address for yarn with hash and all? like this one
```
  resolved "https://registry.yarnpkg.com/caniuse-db/-/caniuse-db-1.0.30000636.tgz#08230e9dd26632193f29c9d935185c6f6f9fd9ef"
```

Thanks.

**Comment by Vinnl** [comment]
@YasserKaddour I believe I just looked [at the registry](https://registry.yarnpkg.com/caniuse-db/) to find the `_shasum` for the latest version.

**Comment by YasserKaddour** [comment]
Thanks, good to know.
