### ISSUE TITLE
Duplicate plugin 'autoprefixer' warning although there is no duplicate

### ISSUE THREAD

**Issue by skleeschulte** [MoOx/postcss-cssnext#388]
I use postcss-cssnext with the postcss-loader in webpack. This is my postcss.config.js script:

    // PostCSS configuration
    
    const postcssConfig = {
        plugins: {
            'postcss-cssnext': {},
            //'autoprefixer': {} // <-- already included in postcss-cssnext
        }
    };
    
    // Compress CSS with cssnano in production
    if (process.env.NODE_ENV === 'production') {
        postcssConfig.plugins['cssnano'] = {};
    }
    
    postcssConfig.plugins['doiuse'] = {};
    
    module.exports = postcssConfig;

When cssnano is added (in production mode), I get the message "Warning: postcss-cssnext found a duplicate plugin ('autoprefixer') in your postcss plugins. This might be inefficient. You should remove 'autoprefixer' from your postcss plugin list since it's already included by postcss-cssnext." If I comment out the line `postcssConfig.plugins['cssnano'] = {};`, the message goes away.

Is this a bug, or do I miss something?

**Comment by Semigradsky** [comment]
`cssnano` has prefixes optimization which use `autoprefixer` (http://cssnano.co/optimisations/autoprefixer/) I see that warning is ok.

**Comment by skleeschulte** [comment]
Alright. So I can savely ignore the warning?

**Comment by Semigradsky** [comment]
Yeah.

**Comment by yordis** [comment]
@Semigradsky why would cssnano or cssnext include autoprefixer by default instead of letting me include it when I want to include it?

**Comment by gflohr** [comment]
@yordis because they depend on autoprefixer.

**Comment by yordis** [comment]
@gflohr right, my point is that autoprefixer is not a `have to have`, I don't understand from high level perspective why the plugins uses autoprefixer.
