### ISSUE TITLE
Nesting and pseudo-classes. Invalid output file order - webpack

### ISSUE THREAD

**Issue by richardadrian** [MoOx/postcss-cssnext#390]
having the same issue as [issue 386](https://github.com/MoOx/postcss-cssnext/issues/386 ) but using webpack. 

The order is invalid which seems to be impacting css precedence.

Downgrading postcss-import did not work.

**Comment by Semigradsky** [comment]
postcss-loader version?

**Comment by richardadrian** [comment]
"postcss-loader": "^2.0.5"

**Comment by Semigradsky** [comment]
postcss-loader 2.x is using PostCSS 6.x
Try donwlgrading postcss-loader to 1.x

**Comment by richardadrian** [comment]
ah, that worked.  Thanks!
