### ISSUE TITLE
React Deprecation Warnings for PropTypes

### ISSUE THREAD

**Issue by LeandraCL** [MoOx/postcss-cssnext#391]
Hi,

There are some deprecation warnings from React since they extracted the PropTypes into a new package called 'prop-types'. Is anybody already working on fixing that? Otherwise, I'll be happy to.

**Comment by MoOx** [comment]
cssnext don't use react. Wrong repo? Or you maybe talking about the website? If so I guess nobody :)

**Comment by LeandraCL** [comment]
:D You're right, sorry, my bad!
