### ISSUE TITLE
Where's the CLI?

### ISSUE THREAD

**Issue by sbrl** [MoOx/postcss-cssnext#394]
This probably doesn't warrant an issue, but I'm really confused. I'm looking for a plain old command line interface to cssnext, but I can't find one. I keep finding this "postcss" thing, but I don't want a preprocessing build system thingy! I just want a plain cli that doesn't some configuration file - the places I want to use it aren't always in a defined 'project' as such.

Is there a command-line interface to cssnext? Where can I find it? If not, are there any alternative project I could use instead?

**Comment by Semigradsky** [comment]
You can use [`postcss-cli`](https://github.com/postcss/postcss-cli).
You should only define postcss-cssnext in `package.json` or `.postcssrc*` file. See details in [`postcss-load-config`](https://github.com/michael-ciniawsky/postcss-load-config#usage)

**Comment by MoOx** [comment]
You can probably build one in less then 10 lines of code an push it on npm in less then 20min :)

**Comment by sbrl** [comment]
Ah, ok. I guess I'll have to use postcss-cli, then. I might investigate creating a quick cli, though - I haven't done that before.
