### ISSUE TITLE
CSS Next error with css variables

### ISSUE THREAD

**Issue by ivikash** [MoOx/postcss-cssnext#399]
Hey, I am trying to use cssnext and I am facing few problems. 

* `Custom property ignored: not scoped to the top-level :root element`
* `variable '--foo-bar' is undefined and used without a fallback`

Basically I have few variables defined at `:root`. Now at certain blocks I am trying to update the values of these variables and at some places I am trying to define new variables. Its giving me the above mentioned errors. I have attached the necessary screenshot. Can you please help.

<img width="1678" alt="screen shot 2017-07-04 at 5 29 37 pm" src="https://user-images.githubusercontent.com/371007/27829275-74d2230e-60de-11e7-8e85-adbe88c3332c.png">

**Comment by MoOx** [comment]
This is a limitation of this transformation. See docs for more explanation https://github.com/postcss/postcss-custom-properties#postcss-custom-properties-
