### ISSUE TITLE
Finish PostCSS 6 compat...

### ISSUE THREAD

**Issue by MoOx** [MoOx/postcss-cssnext#401]
Pretty boring...

- [x] https://github.com/robwierzbowski/node-pixrem/issues/62
- [x] https://github.com/postcss/postcss-color-rgba-fallback/issues/26
- [x] https://github.com/axa-ch/postcss-pseudoelements/issues/12

**Comment by MoOx** [comment]
Any help is appreciated as my time is limited for this project.

**Comment by magsout** [comment]
@MoOx done postcss/postcss-color-rgba-fallback#26

**Comment by MoOx** [comment]
3.0.1 is out
