### ISSUE TITLE
I want to use autoprefixer in the postcss-cssnext,but it's doesn't work

### ISSUE THREAD

**Issue by mov1er** [MoOx/postcss-cssnext#417]
here is my webpack config:
![12312](https://user-images.githubusercontent.com/16483316/30631364-8bff627e-9e16-11e7-8501-0651502c2906.png)

but it's doesn't work at all,other plugins work as well
![sdads](https://user-images.githubusercontent.com/16483316/30631503-07e2d222-9e17-11e7-98c3-955e27c6435a.png)

btw:those are all in a vue-cli project, somebody helps me, pls

**Comment by MoOx** [comment]
Nothing is wrong here. Autoprefixer should add support on what it can depending on your browser scope. Please read carefully autoprefixer doc.

**Comment by mov1er** [comment]
I dont't get it. Then how I can get compiled CSS like next photo by just using postcss-cssnext.
I got next code by adding a postcss.config.js and use autoprefixer.
![asdx](https://user-images.githubusercontent.com/16483316/30631886-9177cee2-9e18-11e7-8c26-b64836f1ad1d.png)

Sorry to bother you.@MoOx

**Comment by MoOx** [comment]
I don't know. postcss.config.js is a thing supported by the loader. So it does not looks like a cssnext problem.
