### ISSUE TITLE
& selector not supporting BEM style naming convention

### ISSUE THREAD

**Issue by theboyWhoCriedWoolf** [MoOx/postcss-cssnext#419]
Hello,

I have recently updated the packages and postCss. I am using the plugin with Webpack as before.

before my css was:

```
.classA {
    &__element {
        // css block code
    }
}
```
Before, this would cover `classA__element` as a class name. Now it seems that this is not possible.

Is there a different way I can implement this?

Thanks in advance for any help.

**Comment by MoOx** [comment]
Not from what I know. I has never been possible per specification :(
Try something like precss maybe.
