### ISSUE TITLE
Cannot install 3.0.x version

### ISSUE THREAD

**Issue by XaveScor** [MoOx/postcss-cssnext#420]
If I try to install 3.0.x version I get this message
```
npm ERR! Unexpected end of JSON input while parsing near '..."shasum":"b0e40d8a344'
```
npm version: 5.5.1
node version: 8.6.0
os: windows 10.14393.447

**Comment by Semigradsky** [comment]
@XaveScor try `npm cache clean --force` and reinstall

**Comment by MoOx** [comment]
Closed due to inactivity.
