### ISSUE TITLE
[FEATURE] Include postcss-reporter to enable warning filtering

### ISSUE THREAD

**Issue by dotnetCarpenter** [MoOx/postcss-cssnext#422]
Due to some plugins emitting a high volume of warnings, the CLI output can be completely useless.

Would it be possible to include [postcss-reporter](https://github.com/postcss/postcss-reporter) so that we have an option to silence some warnings?

More background info can be found here: https://github.com/robwierzbowski/node-pixrem/issues/60

**Comment by MoOx** [comment]
Why not just using postcss-reporter after cssnext?
I don't see why cssnext should handle this.

**Comment by dotnetCarpenter** [comment]
I'm using cssnext because it's bundled with  [nuxt](https://github.com/nuxt/nuxt.js/) and since a lot of people are using cssnext in some bundle or another, it would just be nice if postcss-reporter came in the package. If we instead have to set it up manually, I think it won't be done in most teams.

**Comment by MoOx** [comment]
I really don't think it's a good idea to put this directly in cssnext as it's really not its responsibility. You should ask nuxt to handle that.
