### ISSUE TITLE
Custom media queries not working with alias resolution

### ISSUE THREAD

**Issue by bentranmyriota** [MoOx/postcss-cssnext#430]
Hi guys, 
   I found that the custom media queries doesn't work with @custom-media statements declared in a global.css file which is resolved via alias. I
   My setup is:
+-- shared
|     +-- global.css
+-- myproject
|     +-- componetA
|           +-- style.css
|     +-- webpack.config.js
|     +-- postcss.config.js

global.css
```stylesheet
:root {
    --color: #ffffff;
}
@custom --mobile-viewport (max-width: 700px);
```
style.css
```stylesheet
@import "shared/global.css";
.label {
      color: var(--color);
}
@media (--mobile-viewport) {
    .label {
         color: blue;
    }
}
```
webpack.config.js
```javascript
module.export = {
      resolve: {
           alias: {
                  "shared": path.resolve(__dirname + "/../shared/")
           }
      },
      module: {
            rules: [
                  {
                       test: /\.css$/,
                       use: [
                             { loader: "css-loader" }, 
                             { loader: "postcss-loader", options: { alias: "shared": path.resolve(__dirname + "/../shared/")}}
                       ]
                  },
            ]
      }
}
```
postcss.config.js
```javascript
module.exports = {
    plugins: {
        "postcss-import": {},
        "postcss-cssnext": {}
    }
}
```
Custom properties --color works fine but somehow custom media queries --mobile-viewport didn't work. It seems that there is a bug in custom media queries

**Comment by MoOx** [comment]
I am very surprised you are facing this. Probably a problem with postcss-import.
Try using postcss-reporter to see if any message is send to you.

**Comment by bentranmyriota** [comment]
You are right about postcss-import. It seems that postcss-import doesn't support alias resolution as expected. I have to use this [fix](https://github.com/postcss/postcss-import/issues/190) to resolve the problem.
