### ISSUE TITLE
unexpected custom media behavior

### ISSUE THREAD

**Issue by v1z** [MoOx/postcss-cssnext#437]
If I declare my custom media for retina as
`@custom-media --retina (min-resolution: 192dpi) and (-webkit-min-device-pixel-ratio: 2);`
in output css it would be
`@media (-webkit-min-device-pixel-ratio: 2) and (-webkit-min-device-pixel-ratio: 2), (min-resolution: 192dpi) and (-webkit-min-device-pixel-ratio: 2)`

First part of generated rule breaks the second's part logic, doesn't it?

**Comment by Semigradsky** [comment]
This is `autoprefixer` problem. Just no write redundant `-webkit-min-device-pixel-ratio: 2`:
```css
@custom-media --retina (min-resolution: 192dpi)
```

**Comment by Semigradsky** [comment]
If you no want modify your code, you can clean prefixes before run `postcss`. See https://github.com/postcss/autoprefixer#outdated-prefixes
