### ISSUE TITLE
Using variable in rgba is not interpolated correctly

### ISSUE THREAD

**Issue by raulferras** [MoOx/postcss-cssnext#440]
Having a hexadecimal color defined in a variable:

```
:root {
   --color: #001f3f;
}
```

and using it with `rgba` does not give me the expected result:
```
.style {
    background: rgba(var(--color), .5);
}
```

The output I get is:

```
.style {
     background: rgba(#001f3f, .5);
}
```

**Comment by nolimit-developers** [comment]
@raulferras solution is combine with https://github.com/postcss/postcss-color-function

**Comment by raulferras** [comment]
Will try, thanks!
