### ISSUE TITLE
How to get rid of the source of modern CSS?

### ISSUE THREAD

**Issue by finom** [MoOx/postcss-cssnext#447]
I'm using a bunch of the awesome CSS features but getting a problem with `color` function:

![image](https://user-images.githubusercontent.com/1082083/36481907-07c6399c-171a-11e8-9a29-d33fb28fe356.png)

The `color` function works in Chromium but `lightness` function doesn't. Instead of using the compiled color, the browser uses the "modern" one which is interpreted it as transparent. 

How to remove the source (including `color` calls, custom props etc) from resulting file?

**Comment by MoOx** [comment]
`postcss-cssnext` has been deprecated in favor or `postcss-preset-env`. Read more at https://moox.io/blog/deprecating-cssnext/
