### ISSUE TITLE
Autoprefixer update

### ISSUE THREAD

**Issue by hirokiosame** [MoOx/postcss-cssnext#451]
Can autoprefixer be udpated to 8.1?

https://github.com/postcss/autoprefixer/releases

**Comment by shrpne** [comment]
Autoprefixer 8 dropped `page-break-` fallback.
Please consider including [postcss-page-break](https://github.com/shrpne/postcss-page-break) to cssnext.

**Comment by jonathantneal** [comment]
Possibly resolved by #445

**Comment by MoOx** [comment]
`postcss-cssnext` has been deprecated in favor or `postcss-preset-env`. Read more at https://moox.io/blog/deprecating-cssnext/
