### ISSUE TITLE
Logical properties support

### ISSUE THREAD

**Issue by jhpratt** [MoOx/postcss-cssnext#456]
[Plugin link](https://github.com/jonathantneal/postcss-logical), [spec link](https://www.w3.org/TR/css-logical/) (WD)

This is currently a **stage 3** proposal in cssdb. There are plenty of examples of uses in the links above, so I won't repeat them here.

If wanted, I can try to figure out how to add a plugin myself and submit a PR.

**Comment by jonathantneal** [comment]
Possibly resolved by #445

**Comment by MoOx** [comment]
`postcss-cssnext` has been deprecated in favor or `postcss-preset-env`. Read more at https://moox.io/blog/deprecating-cssnext/
