### ISSUE TITLE
calc(..) adds space between my unit and the resulting integer.

### ISSUE THREAD

**Issue by Praneeth-Pike** [MoOx/postcss-cssnext#458]
I'm not sure if this is a dumb thing, but I'm having issue while using cssnext

**Case 1**
My Code:
`height: calc(20 / 1.618)rem;`

Expected Output:
`height: 12.36094rem`

Output:
`height: 12.36094 rem`

Is my syntax wrong?

**Case 2**
If I put the rem inside like this: `height:calc(20 / 1.618rem)`, 
this is the error: `ERROR in ./node_modules/css-loader??ref--5-1!./node_modules/postcss-loader/lib!./node_modules/sass-loader/lib/loader.js!./src/assets/styles/styles.css 
Module build failed: Error: Cannot divide by "rem", number expected`

**Case 3**
Input : `height: calc(20 / 1.618 rem)`

error: `Module build failed: Error: Parse error on line 1:
    20 / 1.618 rem
    -----------^
    Expecting 'EOF', 'ADD', 'SUB', 'MUL', 'DIV', 'RPAREN', got 'PREFIX'`

**Please help me with the right way to do this**

**Comment by marzelin** [comment]
Have you tried `height: calc(20rem / 1.618);`?

**Comment by jhpratt** [comment]
@Praneeth-Pike Your code isn't valid. Try what @marzelin suggested, as that's the proper way. I _think_ Sass/SCSS allows for what you're doing, but the spec does not.

**Comment by jonathantneal** [comment]
@marzelin has the right answer. Thanks!
