### ISSUE TITLE
deprecation warning messages link may happen broken

### ISSUE THREAD

**Issue by kitsuyui** [MoOx/postcss-cssnext#462]
postcss-cssnext-warn-for-deprecations makes following warning message.

> You are using @apply rule and custom property sets.
This feature won't be included in the next major release of postcss-cssnext.
This most likely won't get any more support from browser vendors as the spec is yet considered deprecated and alternative solutions are being discussed.
Read more about the reason here https://github.com/pascalduez/postcss-apply.

`https://github.com/pascalduez/postcss-apply.` has trailing period (full point), so this may break some console / terminal software link feature.

They have a feature that when they found link like text, it makes hyperlink by shift key.

- [https://github.com/pascalduez/postcss-apply](https://github.com/pascalduez/postcss-apply) ... Okay
- [https://github.com/pascalduez/postcss-apply.](https://github.com/pascalduez/postcss-apply.) ... Not Good

In my environment, iTerm2 (macOS) and xterm (Linux) occurs just this pattern.

**Comment by MoOx** [comment]
`postcss-cssnext` has been deprecated in favor or `postcss-preset-env`. Read more at https://moox.io/blog/deprecating-cssnext/
