### ISSUE TITLE
"Cannot read property '_autoprefixerDisabled' of undefined'"

### ISSUE THREAD

**Issue by miketaylr** [MoOx/postcss-cssnext#47]
I originally filed this over at https://github.com/webcompat/webcompat.com/issues/394.

I used to have:

```
├─┬ grunt-cssnext@0.1.1
│ ├─┬ cssnext@0.2.3
│ │ ├─┬ autoprefixer-core@3.1.2
```

Deleting node_modules and reinstalling I now have:

```
├─┬ grunt-cssnext@0.1.1
│ ├─┬ cssnext@0.2.3
│ │ ├─┬ autoprefixer-core@3.2.0
```

And now `grunt cssnext` fails with `"Cannot read property '_autoprefixerDisabled' of undefined'"`

**Comment by mymai91** [comment]
Good solution. Thanks
