### ISSUE TITLE
extract option fully implemented

### ISSUE THREAD

**Issue by hgl** [MoOx/postcss-cssnext#90]
I have a fully implemented and tested cssnext fork in my [extract branch](https://github.com/hgl/cssnext/tree/extract) that is able to this:

config.js
```json
{
  "features": {
    "customProperties": {
      "variables": {
        "color": "#e00"
      }
    },
    "customMedia": {
      "extensions": {
        "mq2": "screen"
      }
    }
  }
}
```
style.css
```css
:root {
	--width: calc(1px + 1px);
	--width2: var(--width);
}
@custom-media --mq (max-width: 30em);
```
```
cssnext --config config.js --extract style.css
```
=>

```json
{
	"customProperties":{
		"width": "2px",
		"width2": "2px",
		"color": "#e00"
	},
	"customMedia":{
		"mq": "(max-width: 30em)",
		"mq2": "screen"
	}
}
```

From our previous discussion, you were worried the implementation will be a hack.

I just want to demonstrate it's not. I only added an `append` option to the custom properties and custom media plugin, which leaves js defined variable in the css source code.

Will you reconsider merging it? Comparing to defining variables in js, I think it's cleaner and easier to write.

**Comment by MoOx** [comment]
I think you have everything you want from the plugins currently used.

**Comment by hgl** [comment]
Yes, I will revise this PR soon. please consider merging https://github.com/postcss/postcss-custom-media/pull/10

**Comment by MoOx** [comment]
Not sure it's relevant now. Feel free to reopen a PR if it is.
